import type { MindGridCase } from "@/types/mindgrid";

export const SEED_MINDGRID_CASES: MindGridCase[] = [
  // ==========================================
  // EASY CASES (4 Cases)
  // ==========================================
  {
    id: "case_001",
    caseNumber: 1,
    title: "The Missing Prototype",
    difficulty: "EASY",
    summary: "A cutting-edge micro-lens prototype vanished from the secure Cleanroom Beta between 10:10 and 10:20 AM.",
    scenario:
      "At 10:25 AM, Dr. Evans discovered that the titanium housing containing the newly calibrated micro-lens was missing from Cleanroom Beta. The cleanroom operates on electronic keycard access and requires wearing colored visitor/staff scrubs. Four individuals were present on the laboratory floor during the critical window.",
    investigationPoints: 8,
    scoring: {
      parDurationSec: 180,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_alex",
        name: "Dr. Alex Wright",
        role: "Lead Optical Engineer",
        bio: "Designed the micro-lens. Was scheduled to present it at 11:00 AM.",
        initialStatement: "I was in the coffee lounge from 10:05 to 10:30 AM preparing my presentation slides.",
      },
      {
        id: "suspect_brian",
        name: "Brian Vance",
        role: "Contract Lab Technician",
        bio: "Responsible for equipment sterilization. His shift began at 09:30 AM.",
        initialStatement: "I was in the chemical wash bay down the hall the entire morning until Dr. Evans raised the alarm.",
      },
      {
        id: "suspect_clara",
        name: "Clara Zhang",
        role: "Quality Assurance Auditor",
        bio: "Visiting auditor wearing official bright red visitor scrubs.",
        initialStatement: "I was in the main conference room reviewing calibration sheets. I never entered Cleanroom Beta.",
      },
      {
        id: "suspect_david",
        name: "David Ross",
        role: "Facility Security Officer",
        bio: "Has master keycard access to all perimeter doors on the floor.",
        initialStatement: "I was patrolling the server hallway on the east wing between 10:00 and 10:30 AM.",
      },
    ],
    initialClues: [
      { id: "clue_1_1", text: "The prototype was confirmed inside the cleanroom tray at 10:10 AM by the automated inventory scanner." },
      { id: "clue_1_2", text: "At 10:20 AM, the cleanroom pressure seal was breached, triggering an internal log." },
      { id: "clue_1_3", text: "Entry into Cleanroom Beta requires both an active keycard and standard blue or red scrubs." },
    ],
    evidence: [
      {
        id: "ev_1_cctv",
        title: "Cleanroom Hallway CCTV Footage",
        description: "Surveillance camera shows a figure in standard blue technician scrubs entering Cleanroom Beta at 10:13 AM and exiting at 10:17 AM carrying a padded pouch.",
        type: "CCTV",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_brian", "suspect_alex"],
        linkedTimelineEventIds: ["tl_1_2", "tl_1_3"],
      },
      {
        id: "ev_1_keycard",
        title: "Cleanroom Beta Access Door Logs",
        description: "Electronic log confirms Keycard #0412 (issued to Technician Brian Vance) opened Cleanroom Beta door at 10:13 AM. No other keycards were swiped.",
        type: "ACCESS_LOG",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_brian"],
        linkedTimelineEventIds: ["tl_1_2"],
      },
      {
        id: "ev_1_lounge_cctv",
        title: "Coffee Lounge CCTV Footage",
        description: "Camera shows Dr. Alex Wright seated with a laptop continuously from 10:06 AM until 10:28 AM, verified by timestamp.",
        type: "CCTV",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_alex"],
        linkedTimelineEventIds: ["tl_1_1", "tl_1_4"],
      },
      {
        id: "ev_1_locker",
        title: "Technician Locker Inspection",
        description: "Inside Locker #14 (assigned to Brian Vance), investigators found a padded pouch hidden under blue scrubs containing the micro-lens.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_brian"],
        linkedTimelineEventIds: ["tl_1_4"],
      },
      {
        id: "ev_1_washbay_log",
        title: "Chemical Wash Bay Automated Water Log",
        description: "The automated water sensor in the chemical wash bay registered zero water flow between 09:45 AM and 10:45 AM, directly contradicting Brian's claim of working there.",
        type: "CONTRADICTION",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_brian"],
        linkedTimelineEventIds: ["tl_1_2", "tl_1_3"],
      },
    ],
    timeline: [
      { id: "tl_1_1", timeLabel: "10:06 AM", minuteOffset: 6, description: "Dr. Alex Wright sits in Coffee Lounge with laptop.", linkedSuspectIds: ["suspect_alex"], isInitial: true },
      { id: "tl_1_2", timeLabel: "10:13 AM", minuteOffset: 13, description: "Cleanroom Beta door opened via Keycard #0412 by individual in blue scrubs.", linkedSuspectIds: ["suspect_brian"], isInitial: false, unlockWithEvidenceId: "ev_1_keycard" },
      { id: "tl_1_3", timeLabel: "10:17 AM", minuteOffset: 17, description: "Figure in blue scrubs departs Cleanroom Beta with padded pouch.", linkedSuspectIds: ["suspect_brian"], isInitial: false, unlockWithEvidenceId: "ev_1_cctv" },
      { id: "tl_1_4", timeLabel: "10:25 AM", minuteOffset: 25, description: "Dr. Evans discovers prototype missing; alarm sounded.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_brian",
      culpritName: "Brian Vance",
      requiredEvidenceIds: ["ev_1_keycard", "ev_1_cctv", "ev_1_washbay_log"],
      primaryContradictionEvidenceIds: ["ev_1_washbay_log", "ev_1_keycard"],
      expectedTimelineOrder: ["tl_1_1", "tl_1_2", "tl_1_3", "tl_1_4"],
      eliminatedSuspects: {
        suspect_alex: { eliminatedByEvidenceId: "ev_1_lounge_cctv", reason: "Alex was on camera in the coffee lounge continuously from 10:06 to 10:28 AM." },
        suspect_clara: { eliminatedByEvidenceId: "ev_1_cctv", reason: "Clara wore red visitor scrubs; intruder was captured on CCTV wearing blue technician scrubs." },
        suspect_david: { eliminatedByEvidenceId: "ev_1_keycard", reason: "David's master keycard was never used; only Brian's Keycard #0412 unlocked the door." },
      },
      explanation:
        "Brian Vance claimed he was washing equipment in the chemical wash bay all morning. However, automated water logs proved the bay was unused, his keycard #0412 opened the cleanroom at 10:13 AM, CCTV captured a person in blue scrubs matching his uniform, and the prototype was discovered in his locker.",
    },
  },

  {
    id: "case_002",
    caseNumber: 2,
    title: "The Gallery Heist",
    difficulty: "EASY",
    summary: "A Renaissance gold signet ring was stolen from its velvet pedestal during a 10-minute electrical flicker.",
    scenario:
      "At 08:30 PM, the Grand Maritime Gallery experienced a scheduled emergency generator test that dimmed lights for 10 minutes. At 08:45 PM, the curator found the showcase glass removed and the Borgia Signet Ring gone. Four staff members had access to the west gallery wing.",
    investigationPoints: 8,
    scoring: {
      parDurationSec: 180,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_marcus",
        name: "Marcus Cole",
        role: "Night Security Guard",
        bio: "Stationed at the west wing checkpoint. Claims he was patrolling the outdoor courtyard.",
        initialStatement: "I went outside to inspect the perimeter gate from 08:25 to 08:40 PM because of the generator test.",
      },
      {
        id: "suspect_elena",
        name: "Elena Rostova",
        role: "Restoration Specialist",
        bio: "Had workshop keys on the second floor above the gallery.",
        initialStatement: "I was on a live video conference with a museum curator in Vienna from 08:15 to 08:50 PM.",
      },
      {
        id: "suspect_toby",
        name: "Toby Miller",
        role: "Lighting Technician",
        bio: "Supervised the power switchover in the basement breaker room.",
        initialStatement: "I was at the main breaker board with the facility supervisor until 08:42 PM.",
      },
      {
        id: "suspect_sonia",
        name: "Sonia Reed",
        role: "Gallery Docent",
        bio: "Was locking up souvenir stands in the north reception atrium.",
        initialStatement: "I was in the front lobby counting register cash in view of the public cameras.",
      },
    ],
    initialClues: [
      { id: "clue_2_1", text: "The display glass was unscrewed with a specialized 4mm hex key used by gallery maintenance staff." },
      { id: "clue_2_2", text: "The theft occurred between 08:30 and 08:40 PM when secondary motion alarms were rebooting." },
      { id: "clue_2_3", text: "The courtyard exit door records magnetic badge locks." },
    ],
    evidence: [
      {
        id: "ev_2_courtyard_log",
        title: "Courtyard Perimeter Gate Door Log",
        description: "The courtyard security door log shows NO badge scans between 08:00 PM and 09:00 PM. Marcus never opened the door to go outside as claimed.",
        type: "CONTRADICTION",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_marcus"],
        linkedTimelineEventIds: ["tl_2_2"],
      },
      {
        id: "ev_2_showcase_cctv",
        title: "Backup Low-Light Camera Footage",
        description: "Low-light camera shows an individual with a security guard radio and flashlight removing the glass pedestal at 08:34 PM.",
        type: "CCTV",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_marcus"],
        linkedTimelineEventIds: ["tl_2_3"],
      },
      {
        id: "ev_2_elena_call",
        title: "Elena's Video Conference Call Record",
        description: "Vienna Museum IT department verified Elena's unbroken screen-sharing and webcam session from 08:15 to 08:50 PM in her 2nd floor studio.",
        type: "STATEMENT",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_elena"],
        linkedTimelineEventIds: ["tl_2_1"],
      },
      {
        id: "ev_2_breaker_log",
        title: "Basement Supervisor Witness Log",
        description: "Facility supervisor confirms Toby was standing beside him at the breaker board throughout the entire power cycle until 08:42 PM.",
        type: "ACCESS_LOG",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_toby"],
        linkedTimelineEventIds: ["tl_2_2"],
      },
    ],
    timeline: [
      { id: "tl_2_1", timeLabel: "08:15 PM", minuteOffset: 15, description: "Elena begins verified video call in upstairs restoration workshop.", linkedSuspectIds: ["suspect_elena"], isInitial: true },
      { id: "tl_2_2", timeLabel: "08:30 PM", minuteOffset: 30, description: "Generator test starts; motion sensors reboot. Marcus claims he exited to courtyard.", linkedSuspectIds: ["suspect_marcus"], isInitial: false, unlockWithEvidenceId: "ev_2_courtyard_log" },
      { id: "tl_2_3", timeLabel: "08:34 PM", minuteOffset: 34, description: "Figure with guard radio and flashlight opens pedestal case.", linkedSuspectIds: ["suspect_marcus"], isInitial: false, unlockWithEvidenceId: "ev_2_showcase_cctv" },
      { id: "tl_2_4", timeLabel: "08:45 PM", minuteOffset: 45, description: "Curator discovers showcase opened and ring missing.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_marcus",
      culpritName: "Marcus Cole",
      requiredEvidenceIds: ["ev_2_courtyard_log", "ev_2_showcase_cctv"],
      primaryContradictionEvidenceIds: ["ev_2_courtyard_log"],
      expectedTimelineOrder: ["tl_2_1", "tl_2_2", "tl_2_3", "tl_2_4"],
      eliminatedSuspects: {
        suspect_elena: { eliminatedByEvidenceId: "ev_2_elena_call", reason: "Elena was on a verified live video call from 08:15 to 08:50 PM." },
        suspect_toby: { eliminatedByEvidenceId: "ev_2_breaker_log", reason: "Toby was in the basement with the facility supervisor until 08:42 PM." },
        suspect_sonia: { eliminatedByEvidenceId: "ev_2_showcase_cctv", reason: "Intruder was equipped with security guard radio and flashlight in west wing; Sonia was in the north lobby." },
      },
      explanation:
        "Marcus claimed he spent the generator test outside patrolling the courtyard, but gate sensor logs prove the courtyard door was never opened. Low-light footage captured someone carrying a guard radio taking the ring at 08:34 PM.",
    },
  },

  {
    id: "case_003",
    caseNumber: 3,
    title: "The Midnight Express",
    difficulty: "EASY",
    summary: "A passenger's emerald necklace disappeared from private Sleeper Cabin 4 during a mountain tunnel transit.",
    scenario:
      "Aboard the luxury Alpine Express, Lady Cynthia reported her emerald necklace stolen from her vanity between 11:40 PM and 11:55 PM while the train passed through the 15-minute Gotthard Tunnel. The carriage corridor was locked from both ends.",
    investigationPoints: 8,
    scoring: {
      parDurationSec: 180,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_julian",
        name: "Julian Croft",
        role: "Cabin Attendant",
        bio: "Had master key for the sleeper compartment carriage.",
        initialStatement: "I was in the dining car serving tea to passengers from 11:35 PM until midnight.",
      },
      {
        id: "suspect_victor",
        name: "Victor Vance",
        role: "Passenger in Cabin 3",
        bio: "Wealthy art collector traveling adjacent to Lady Cynthia.",
        initialStatement: "I fell asleep at 11:15 PM and did not leave my bed until morning.",
      },
      {
        id: "suspect_nadia",
        name: "Nadia Bell",
        role: "Train Conductor",
        bio: "Stationed in the rear brake cabin checking electrical gauges.",
        initialStatement: "I remained inside the rear cabin logging tunnel air pressure gauges with the assistant engineer.",
      },
    ],
    initialClues: [
      { id: "clue_3_1", text: "Cabin 4 door was unlocked with a service skeleton key without any signs of forced entry." },
      { id: "clue_3_2", text: "The thief left behind a monogrammed handkerchief embroidered with 'J.C.' on the vanity carpet." },
    ],
    evidence: [
      {
        id: "ev_3_dining_log",
        title: "Dining Car Service Ledger",
        description: "Dining car head steward states Julian Croft stepped away at 11:38 PM claiming he needed to restock linens and did not return until 11:56 PM.",
        type: "CONTRADICTION",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_julian"],
        linkedTimelineEventIds: ["tl_3_2", "tl_3_3"],
      },
      {
        id: "ev_3_handkerchief",
        title: "Forensic Analysis of Handkerchief",
        description: "The handkerchief left in Cabin 4 matches Julian Croft's uniform issue and carries traces of lavender linen spray used by attendants.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_julian"],
        linkedTimelineEventIds: ["tl_3_3"],
      },
      {
        id: "ev_3_conductor_gauge",
        title: "Rear Cabin Pressure Telemetry Logs",
        description: "Telemetry logs show continuous physical sign-offs by Nadia Bell every 3 minutes from 11:30 PM to 12:05 AM alongside the engineer.",
        type: "ACCESS_LOG",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_nadia"],
        linkedTimelineEventIds: ["tl_3_1"],
      },
    ],
    timeline: [
      { id: "tl_3_1", timeLabel: "11:35 PM", minuteOffset: 35, description: "Train approaches mountain tunnel; Lady Cynthia leaves cabin for observation car.", linkedSuspectIds: [], isInitial: true },
      { id: "tl_3_2", timeLabel: "11:38 PM", minuteOffset: 38, description: "Julian Croft departs dining car unobserved.", linkedSuspectIds: ["suspect_julian"], isInitial: false, unlockWithEvidenceId: "ev_3_dining_log" },
      { id: "tl_3_3", timeLabel: "11:46 PM", minuteOffset: 46, description: "Cabin 4 accessed via attendant master skeleton key.", linkedSuspectIds: ["suspect_julian"], isInitial: false, unlockWithEvidenceId: "ev_3_handkerchief" },
      { id: "tl_3_4", timeLabel: "11:58 PM", minuteOffset: 58, description: "Lady Cynthia returns to cabin and discovers emerald necklace stolen.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_julian",
      culpritName: "Julian Croft",
      requiredEvidenceIds: ["ev_3_dining_log", "ev_3_handkerchief"],
      primaryContradictionEvidenceIds: ["ev_3_dining_log"],
      expectedTimelineOrder: ["tl_3_1", "tl_3_2", "tl_3_3", "tl_3_4"],
      eliminatedSuspects: {
        suspect_victor: { eliminatedByEvidenceId: "ev_3_handkerchief", reason: "Victor had no skeleton key and the monogrammed attendant handkerchief belonged to Julian." },
        suspect_nadia: { eliminatedByEvidenceId: "ev_3_conductor_gauge", reason: "Nadia's presence in the rear cabin was verified every 3 minutes by telemetry logs." },
      },
      explanation:
        "Julian Croft claimed he served tea in the dining car without interruption, but the head steward confirmed he vanished for 18 minutes. His master skeleton key was used, and his personalized monogrammed handkerchief was left on the vanity.",
    },
  },

  {
    id: "case_004",
    caseNumber: 4,
    title: "The Server Room Breach",
    difficulty: "EASY",
    summary: "Confidential customer encryption keys were copied onto an unauthorized USB drive at 02:15 AM.",
    scenario:
      "At 02:18 AM, the automated intrusion detection system of NovaBank alerted security that a root-level encryption key dump had completed on Server Rack Alpha. Four on-duty night shift staff members were present in the IT building.",
    investigationPoints: 8,
    scoring: {
      parDurationSec: 180,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_kevin",
        name: "Kevin Park",
        role: "Systems Administrator",
        bio: "Had root console credentials and server cage biometric clearance.",
        initialStatement: "I was eating dinner in the 1st-floor cafeteria from 02:00 to 02:30 AM.",
      },
      {
        id: "suspect_rachel",
        name: "Rachel Green",
        role: "Network Security Analyst",
        bio: "Monitored the SIEM threat console in the Security Operations Center.",
        initialStatement: "I was at my multi-monitor desk in SOC Room 204 analyzing firewall pings.",
      },
      {
        id: "suspect_oscar",
        name: "Oscar Diaz",
        role: "Building Janitor",
        bio: "Cleaning offices on the second floor.",
        initialStatement: "I was vacuuming the executive boardroom on floor 3 all hour.",
      },
    ],
    initialClues: [
      { id: "clue_4_1", text: "The USB drive was inserted into Terminal Alpha-1 at exactly 02:12 AM and unmounted at 02:17 AM." },
      { id: "clue_4_2", text: "Physical entry to Server Cage Alpha requires an iris scan or high-security smartcard." },
    ],
    evidence: [
      {
        id: "ev_4_cafeteria_cctv",
        title: "Cafeteria Surveillance Video",
        description: "Cafeteria CCTV shows the cafeteria was completely dark and empty between 02:00 and 02:30 AM. Kevin was not there.",
        type: "CONTRADICTION",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_kevin"],
        linkedTimelineEventIds: ["tl_4_2"],
      },
      {
        id: "ev_4_iris_log",
        title: "Server Cage Iris Scanner Audit",
        description: "Iris scanner record confirms Kevin Park authenticated and opened Server Cage Alpha door at 02:11 AM.",
        type: "ACCESS_LOG",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_kevin"],
        linkedTimelineEventIds: ["tl_4_2"],
      },
      {
        id: "ev_4_soc_keystrokes",
        title: "SOC Room 204 Keystroke Audit",
        description: "Continuous telemetry confirms Rachel's biometric keyboard logged active firewall analysis keystrokes every 10 seconds from 02:00 to 02:30 AM.",
        type: "STATEMENT",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_rachel"],
        linkedTimelineEventIds: ["tl_4_1"],
      },
    ],
    timeline: [
      { id: "tl_4_1", timeLabel: "02:00 AM", minuteOffset: 0, description: "Night shift systems maintenance window starts.", linkedSuspectIds: [], isInitial: true },
      { id: "tl_4_2", timeLabel: "02:11 AM", minuteOffset: 11, description: "Iris scanner logs Kevin Park entering Server Cage Alpha.", linkedSuspectIds: ["suspect_kevin"], isInitial: false, unlockWithEvidenceId: "ev_4_iris_log" },
      { id: "tl_4_3", timeLabel: "02:12 AM", minuteOffset: 12, description: "Unauthorized USB drive mounted on Terminal Alpha-1.", linkedSuspectIds: ["suspect_kevin"], isInitial: true },
      { id: "tl_4_4", timeLabel: "02:18 AM", minuteOffset: 18, description: "Intrusion detection alarm triggers on completed dump.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_kevin",
      culpritName: "Kevin Park",
      requiredEvidenceIds: ["ev_4_cafeteria_cctv", "ev_4_iris_log"],
      primaryContradictionEvidenceIds: ["ev_4_cafeteria_cctv", "ev_4_iris_log"],
      expectedTimelineOrder: ["tl_4_1", "tl_4_2", "tl_4_3", "tl_4_4"],
      eliminatedSuspects: {
        suspect_rachel: { eliminatedByEvidenceId: "ev_4_soc_keystrokes", reason: "Rachel was actively typing in SOC 204 with continuous biometric keystrokes." },
        suspect_oscar: { eliminatedByEvidenceId: "ev_4_iris_log", reason: "Oscar lacked iris scan clearance; only Kevin's iris scan unlocked the server cage." },
      },
      explanation:
        "Kevin claimed he was in the cafeteria, but cafeteria CCTV proved the room was empty. His iris scan registered at Server Cage Alpha at 02:11 AM, one minute before the unauthorized USB copy began.",
    },
  },

  // ==========================================
  // MEDIUM CASES (5 Cases)
  // ==========================================
  {
    id: "case_005",
    caseNumber: 5,
    title: "The Vanishing Ledger",
    difficulty: "MEDIUM",
    summary: "A confidential offshore tax audit binder was removed from the Chief Financial Officer's safe on Floor 18.",
    scenario:
      "At 07:45 PM on Friday, CFO Gerald Sterling returned to his office after a partner dinner to find his wall safe unlocked and the confidential audit ledger missing. The 18th floor was locked for the weekend at 06:30 PM. Four employees remained in the building.",
    investigationPoints: 10,
    scoring: {
      parDurationSec: 240,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_arthur",
        name: "Arthur Pendelton",
        role: "Senior Partner",
        bio: "Subject of the impending tax audit. Left dinner early claiming a migraine.",
        initialStatement: "I left the dinner at 06:45 PM and took a taxi directly to my home in Greenwich. I arrived home by 07:30 PM.",
      },
      {
        id: "suspect_chloe",
        name: "Chloe Sims",
        role: "Executive Assistant",
        bio: "Knows the safe's dial sequence. Was seen organizing files on Floor 17.",
        initialStatement: "I was on Floor 17 until 07:15 PM packing weekend files, then took the express elevator straight to the lobby.",
      },
      {
        id: "suspect_felix",
        name: "Felix Gomez",
        role: "Junior Compliance Auditor",
        bio: "Discovered accounting discrepancies in the ledger earlier in the week.",
        initialStatement: "I was working in the 16th-floor library until 08:00 PM with the library sign-in sheet.",
      },
      {
        id: "suspect_maya",
        name: "Maya Lin",
        role: "IT Network Administrator",
        bio: "Had badge access to all floor stairwells to service network closets.",
        initialStatement: "I was in the basement server room resetting the backup generator from 06:45 to 07:45 PM.",
      },
    ],
    initialClues: [
      { id: "clue_5_1", text: "The safe was opened without damage using the correct 6-digit combination." },
      { id: "clue_5_2", text: "Floor 18 elevator access requires an executive keycard after 06:30 PM." },
      { id: "clue_5_3", text: "A distinct aroma of expensive cuban cigar smoke lingered in the CFO's office." },
    ],
    evidence: [
      {
        id: "ev_5_taxi_receipt",
        title: "Arthur's Taxi Dispatch Records",
        description: "Dispatch logs confirm Arthur's hailed taxi picked him up outside the restaurant at 06:47 PM and dropped him off at the office building at 07:02 PM, NOT at his home.",
        type: "CONTRADICTION",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_arthur"],
        linkedTimelineEventIds: ["tl_5_1", "tl_5_2"],
      },
      {
        id: "ev_5_elevator_badge",
        title: "Executive Elevator Badge Log",
        description: "Executive Badge #003 (assigned to Senior Partner Arthur Pendelton) swiped for Floor 18 at 07:05 PM.",
        type: "ACCESS_LOG",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_arthur"],
        linkedTimelineEventIds: ["tl_5_2"],
      },
      {
        id: "ev_5_chloe_cctv",
        title: "Lobby Turnstile CCTV Footage",
        description: "Lobby cameras confirm Chloe Sims passed through the front exit turnstiles at 07:18 PM with a small canvas purse, matching her statement.",
        type: "CCTV",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_chloe"],
        linkedTimelineEventIds: ["tl_5_3"],
      },
      {
        id: "ev_5_safe_scrap",
        title: "Physical Safe Latch Residue",
        description: "Forensic swabs from the safe handle reveal ashes of Cohiba Siglo VI cigar tobacco, a luxury brand imported exclusively by Arthur Pendelton.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_arthur"],
        linkedTimelineEventIds: ["tl_5_2"],
      },
      {
        id: "ev_5_felix_library",
        title: "16th Floor Library Security Sign-in",
        description: "Library CCTV and digital sign-in corroborate Felix was at his study carrel continuously from 06:15 PM until 08:00 PM.",
        type: "STATEMENT",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_felix"],
        linkedTimelineEventIds: ["tl_5_1", "tl_5_4"],
      },
    ],
    timeline: [
      { id: "tl_5_1", timeLabel: "06:45 PM", minuteOffset: 45, description: "Arthur leaves partner dinner claiming migraine.", linkedSuspectIds: ["suspect_arthur"], isInitial: true },
      { id: "tl_5_2", timeLabel: "07:05 PM", minuteOffset: 65, description: "Executive Badge #003 accesses Floor 18 elevator.", linkedSuspectIds: ["suspect_arthur"], isInitial: false, unlockWithEvidenceId: "ev_5_elevator_badge" },
      { id: "tl_5_3", timeLabel: "07:18 PM", minuteOffset: 78, description: "Chloe exits lobby turnstile with small canvas purse.", linkedSuspectIds: ["suspect_chloe"], isInitial: false, unlockWithEvidenceId: "ev_5_chloe_cctv" },
      { id: "tl_5_4", timeLabel: "07:45 PM", minuteOffset: 105, description: "CFO Gerald Sterling returns and finds safe emptied.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_arthur",
      culpritName: "Arthur Pendelton",
      requiredEvidenceIds: ["ev_5_taxi_receipt", "ev_5_elevator_badge", "ev_5_safe_scrap"],
      primaryContradictionEvidenceIds: ["ev_5_taxi_receipt"],
      expectedTimelineOrder: ["tl_5_1", "tl_5_2", "tl_5_3", "tl_5_4"],
      eliminatedSuspects: {
        suspect_chloe: { eliminatedByEvidenceId: "ev_5_chloe_cctv", reason: "Chloe left the building at 07:18 PM carrying only a small purse that could not hold a 4-inch binder." },
        suspect_felix: { eliminatedByEvidenceId: "ev_5_felix_library", reason: "Felix was on camera in the 16th floor library until 08:00 PM." },
        suspect_maya: { eliminatedByEvidenceId: "ev_5_safe_scrap", reason: "Maya does not smoke cigars, and Arthur's badge was used on the Floor 18 elevator." },
      },
      explanation:
        "Arthur claimed he took a taxi directly home to Greenwich, but taxi dispatch logs proved his cab dropped him at the office at 07:02 PM. His executive keycard opened Floor 18 at 07:05 PM, and his exclusive Cohiba cigar ash was discovered on the safe handle.",
    },
  },

  {
    id: "case_006",
    caseNumber: 6,
    title: "The Poisoned Goblet",
    difficulty: "MEDIUM",
    summary: "Lord Harrington collapsed after drinking vintage port wine during an exclusive five-course estate banquet.",
    scenario:
      "At 09:15 PM during the dessert course at Blackwood Manor, Lord Harrington took a sip of 1982 Vintage Port and suffered sudden belladonna poisoning. The port was uncorked in the private butler pantry and served to only three guests at the head table.",
    investigationPoints: 10,
    scoring: {
      parDurationSec: 240,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_edward",
        name: "Edward Harrington",
        role: "Nephew & Sole Heir",
        bio: "Stood to inherit the estate if Lord Harrington passed away before signing a revised will.",
        initialStatement: "I was sitting on the terrace smoking with the ambassador from 09:00 to 09:15 PM.",
      },
      {
        id: "suspect_beatrice",
        name: "Lady Beatrice",
        role: "Lord Harrington's Business Partner",
        bio: "In a bitter legal dispute over overseas shipping shares.",
        initialStatement: "I was at the main dining table talking with the Countess all through dessert.",
      },
      {
        id: "suspect_giles",
        name: "Giles Thornton",
        role: "Head Butler",
        bio: "Sole keeper of the wine cellar and pantry keys for 25 years.",
        initialStatement: "I decanted the wine at 09:05 PM and handed the decanter directly to server Paul.",
      },
      {
        id: "suspect_paul",
        name: "Paul Higgins",
        role: "Temporary Banquet Server",
        bio: "Hired for the evening through a domestic staffing agency.",
        initialStatement: "I poured Lord Harrington's goblet directly after receiving the decanter from Mr. Giles.",
      },
    ],
    initialClues: [
      { id: "clue_6_1", text: "Belladonna extract was detected inside Lord Harrington's goblet, but NOT in the main decanter." },
      { id: "clue_6_2", text: "The poison had to be placed directly on the goblet glass rim or poured into the glass itself before serving." },
    ],
    evidence: [
      {
        id: "ev_6_terrace_statement",
        title: "Ambassador's Eyewitness Statement",
        description: "The French Ambassador testifies Edward stepped away from the terrace at 09:04 PM saying he needed to check his coat in the service pantry, returning at 09:12 PM.",
        type: "CONTRADICTION",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_edward"],
        linkedTimelineEventIds: ["tl_6_1", "tl_6_2"],
      },
      {
        id: "ev_6_pantry_vial",
        title: "Pantry Coat Rack Search",
        description: "Inside the pocket of Edward Harrington's cashmere overcoat in the pantry vestibule, police found an empty amber glass dropper bottle containing traces of belladonna.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_edward"],
        linkedTimelineEventIds: ["tl_6_2"],
      },
      {
        id: "ev_6_table_cctv",
        title: "Dining Hall Chandelier Camera",
        description: "Overhead footage shows Lady Beatrice seated continuously at the dining table with the Countess from 08:50 to 09:20 PM.",
        type: "CCTV",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_beatrice"],
        linkedTimelineEventIds: ["tl_6_1", "tl_6_3"],
      },
      {
        id: "ev_6_decanter_swab",
        title: "Wine Decanter Toxicological Report",
        description: "Toxicology confirms the wine inside the decanter handled by Giles and Paul was 100% pure and untainted, proving the poison was applied to the goblet directly in the pantry.",
        type: "DIRECT_EVIDENCE",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_giles", "suspect_paul"],
        linkedTimelineEventIds: ["tl_6_2", "tl_6_3"],
      },
    ],
    timeline: [
      { id: "tl_6_1", timeLabel: "09:00 PM", minuteOffset: 0, description: "Dessert course begins; Edward leaves terrace unobserved.", linkedSuspectIds: ["suspect_edward"], isInitial: true },
      { id: "tl_6_2", timeLabel: "09:06 PM", minuteOffset: 6, description: "Edward accesses butler pantry while glasses are pre-staged.", linkedSuspectIds: ["suspect_edward"], isInitial: false, unlockWithEvidenceId: "ev_6_terrace_statement" },
      { id: "tl_6_3", timeLabel: "09:10 PM", minuteOffset: 10, description: "Server Paul pours untainted wine from decanter into pre-staged goblet.", linkedSuspectIds: ["suspect_paul"], isInitial: false, unlockWithEvidenceId: "ev_6_decanter_swab" },
      { id: "tl_6_4", timeLabel: "09:15 PM", minuteOffset: 15, description: "Lord Harrington drinks from goblet and collapses.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_edward",
      culpritName: "Edward Harrington",
      requiredEvidenceIds: ["ev_6_terrace_statement", "ev_6_pantry_vial", "ev_6_decanter_swab"],
      primaryContradictionEvidenceIds: ["ev_6_terrace_statement"],
      expectedTimelineOrder: ["tl_6_1", "tl_6_2", "tl_6_3", "tl_6_4"],
      eliminatedSuspects: {
        suspect_beatrice: { eliminatedByEvidenceId: "ev_6_table_cctv", reason: "Beatrice remained at the dining table on camera throughout the entire dessert course." },
        suspect_giles: { eliminatedByEvidenceId: "ev_6_decanter_swab", reason: "The wine decanter prepared by Giles was completely untainted." },
        suspect_paul: { eliminatedByEvidenceId: "ev_6_pantry_vial", reason: "The poison dropper bottle was found in Edward's coat pocket, not on Paul." },
      },
      explanation:
        "Edward claimed he was smoking on the terrace with the ambassador the entire time, but the ambassador stated Edward slipped away for 8 minutes. During this window, Edward entered the pantry, coated his uncle's pre-staged goblet with belladonna from an amber vial found in his coat, and returned before the wine was poured.",
    },
  },

  {
    id: "case_007",
    caseNumber: 7,
    title: "The Clocktower Sabotage",
    difficulty: "MEDIUM",
    summary: "The historic city clocktower mechanism was deliberately jammed with an iron rod right before the Centennial Chime.",
    scenario:
      "At 11:50 AM, ten minutes before the city's 100-year celebration, the Great Bell's escapement gear was jammed by a forged iron rod, stopping the clock. Access to the clockwork loft is restricted to four municipal maintenance engineers.",
    investigationPoints: 10,
    scoring: {
      parDurationSec: 240,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_harlan",
        name: "Harlan Cross",
        role: "Retired Master Horologist",
        bio: "Opposed the city's plan to replace the mechanical gears with an electronic system.",
        initialStatement: "I was at the plaza bakery across the street having coffee from 11:30 to 12:10 PM.",
      },
      {
        id: "suspect_carla",
        name: "Carla Ramos",
        role: "Municipal Chief Engineer",
        bio: "Advocated for the new $2M digital clock contract.",
        initialStatement: "I was giving an interview to the local news crew in front of City Hall until 12:00 PM.",
      },
      {
        id: "suspect_samuel",
        name: "Samuel Drake",
        role: "Apprentice Clocksmith",
        bio: "Owed money to gambling syndicates who bet heavily on the chime failing.",
        initialStatement: "I was cleaning the lower bell tower stairs between 11:30 and 11:55 AM.",
      },
      {
        id: "suspect_clive",
        name: "Clive Sterling",
        role: "City Historian",
        bio: "Was documenting the gears for a commemorative book.",
        initialStatement: "I was in the archives on the 2nd floor organizing photographic negatives.",
      },
    ],
    initialClues: [
      { id: "clue_7_1", text: "The iron rod used to jam the gear was wrapped in a greasy workshop rag marked 'DRAKE FORGE'." },
      { id: "clue_7_2", text: "The loft door lock shows no sign of forced entry." },
    ],
    evidence: [
      {
        id: "ev_7_bakery_receipt",
        title: "Plaza Bakery Time-Stamped Receipt",
        description: "Bakery register and staff confirm Harlan Cross was seated by the bakery window from 11:28 AM until 12:15 PM.",
        type: "STATEMENT",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_harlan"],
        linkedTimelineEventIds: ["tl_7_1"],
      },
      {
        id: "ev_7_news_footage",
        title: "Local News Live Broadcast Footage",
        description: "Televised news tape shows Carla Ramos on live camera from 11:35 AM until 12:02 PM continuously in front of City Hall.",
        type: "CCTV",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_carla"],
        linkedTimelineEventIds: ["tl_7_1", "tl_7_3"],
      },
      {
        id: "ev_7_drake_bet",
        title: "Betting Slip & Phone Records",
        description: "Police discovered an offshore betting slip on Samuel Drake's phone placing a 10:1 bet that the clock would fail to chime at noon, placed at 11:15 AM.",
        type: "CONTRADICTION",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_samuel"],
        linkedTimelineEventIds: ["tl_7_2"],
      },
      {
        id: "ev_7_forge_tool",
        title: "Loft Floor Grease & Fingerprint Analysis",
        description: "Fingerprints on the iron rod and the Drake Forge rag match Samuel Drake, who holds the duplicate loft key #3.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_samuel"],
        linkedTimelineEventIds: ["tl_7_2", "tl_7_3"],
      },
    ],
    timeline: [
      { id: "tl_7_1", timeLabel: "11:30 AM", minuteOffset: 30, description: "Centennial crowd gathers in plaza; Carla begins live TV interview.", linkedSuspectIds: ["suspect_carla"], isInitial: true },
      { id: "tl_7_2", timeLabel: "11:45 AM", minuteOffset: 45, description: "Samuel Drake ascends to gear loft with iron rod from his family forge.", linkedSuspectIds: ["suspect_samuel"], isInitial: false, unlockWithEvidenceId: "ev_7_forge_tool" },
      { id: "tl_7_3", timeLabel: "11:50 AM", minuteOffset: 50, description: "Clock mechanism jams; escapement wheel halts.", linkedSuspectIds: [], isInitial: true },
      { id: "tl_7_4", timeLabel: "12:00 PM", minuteOffset: 60, description: "Centennial Chime fails to sound.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_samuel",
      culpritName: "Samuel Drake",
      requiredEvidenceIds: ["ev_7_drake_bet", "ev_7_forge_tool"],
      primaryContradictionEvidenceIds: ["ev_7_drake_bet"],
      expectedTimelineOrder: ["tl_7_1", "tl_7_2", "tl_7_3", "tl_7_4"],
      eliminatedSuspects: {
        suspect_harlan: { eliminatedByEvidenceId: "ev_7_bakery_receipt", reason: "Harlan was at the bakery window on record throughout the window." },
        suspect_carla: { eliminatedByEvidenceId: "ev_7_news_footage", reason: "Carla was on live television broadcast in front of City Hall until 12:02 PM." },
        suspect_clive: { eliminatedByEvidenceId: "ev_7_forge_tool", reason: "The fingerprints and custom forged tool belonged directly to Samuel Drake." },
      },
      explanation:
        "Samuel Drake placed a massive bet against the clock chiming at noon. He used his duplicate key to access the loft at 11:45 AM and jammed the escapement gear with an iron rod wrapped in his own workshop rag.",
    },
  },

  {
    id: "case_008",
    caseNumber: 8,
    title: "The Architect's Blueprints",
    difficulty: "MEDIUM",
    summary: "Confidential structural blueprints for the new city stadium were stolen during a rainy evening power blackout.",
    scenario:
      "At 06:40 PM during a severe rainstorm, the design studio of Foster & Partners suffered a localized 10-minute circuit trip. When emergency lighting activated at 06:50 PM, the master stadium blueprint roll had been cut from its drafting table.",
    investigationPoints: 10,
    scoring: {
      parDurationSec: 240,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_damon",
        name: "Damon Vance",
        role: "Rival Firm Consultant",
        bio: "Visiting to review joint zoning permits.",
        initialStatement: "I was waiting by the front reception lobby near the dry umbrella stands the whole time.",
      },
      {
        id: "suspect_lauren",
        name: "Lauren Croft",
        role: "Senior Draftsperson",
        bio: "Had recently resigned to join a competitor.",
        initialStatement: "I was downstairs in the cafeteria buying a hot tea from 06:35 to 06:55 PM.",
      },
      {
        id: "suspect_nigel",
        name: "Nigel Scott",
        role: "Office Facility Manager",
        bio: "Was in the breaker closet restoring the power switch.",
        initialStatement: "I was resetting breaker #4 in the basement from the moment the lights went out.",
      },
    ],
    initialClues: [
      { id: "clue_8_1", text: "Fresh muddy rainwater shoe prints were found next to the drafting table on Floor 3." },
      { id: "clue_8_2", text: "The studio's rear fire stairwell was propped open with a drafting eraser." },
    ],
    evidence: [
      {
        id: "ev_8_damon_raincoat",
        title: "Damon's Trench Coat & Boots Inspection",
        description: "Damon's trench coat was dripping wet and his boot treads perfectly matched the muddy clay soil patterns found beside the drafting table on Floor 3.",
        type: "CONTRADICTION",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_damon"],
        linkedTimelineEventIds: ["tl_8_2"],
      },
      {
        id: "ev_8_reception_cctv",
        title: "Reception Lobby Camera",
        description: "Lobby camera shows Damon Vance leaving the reception area into the rear stairwell at 06:38 PM and returning with a concealed long cylinder at 06:48 PM.",
        type: "CCTV",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_damon"],
        linkedTimelineEventIds: ["tl_8_2", "tl_8_3"],
      },
      {
        id: "ev_8_cafeteria_receipt",
        title: "Cafeteria POS Transaction Record",
        description: "Time-stamped register receipt and cashier testimony confirm Lauren bought tea and sat in the cafeteria at 06:37 PM.",
        type: "ACCESS_LOG",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_lauren"],
        linkedTimelineEventIds: ["tl_8_1"],
      },
    ],
    timeline: [
      { id: "tl_8_1", timeLabel: "06:35 PM", minuteOffset: 35, description: "Rainstorm intensifies; Lauren orders tea in basement cafeteria.", linkedSuspectIds: ["suspect_lauren"], isInitial: true },
      { id: "tl_8_2", timeLabel: "06:40 PM", minuteOffset: 40, description: "Circuit trips; Damon ascends rear fire stairwell with wet boots.", linkedSuspectIds: ["suspect_damon"], isInitial: false, unlockWithEvidenceId: "ev_8_reception_cctv" },
      { id: "tl_8_3", timeLabel: "06:48 PM", minuteOffset: 48, description: "Damon returns to lobby with concealed blueprint cylinder.", linkedSuspectIds: ["suspect_damon"], isInitial: false, unlockWithEvidenceId: "ev_8_reception_cctv" },
      { id: "tl_8_4", timeLabel: "06:50 PM", minuteOffset: 50, description: "Lights restored; cut blueprint discovered on drafting table.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_damon",
      culpritName: "Damon Vance",
      requiredEvidenceIds: ["ev_8_damon_raincoat", "ev_8_reception_cctv"],
      primaryContradictionEvidenceIds: ["ev_8_damon_raincoat", "ev_8_reception_cctv"],
      expectedTimelineOrder: ["tl_8_1", "tl_8_2", "tl_8_3", "tl_8_4"],
      eliminatedSuspects: {
        suspect_lauren: { eliminatedByEvidenceId: "ev_8_cafeteria_receipt", reason: "Lauren was in the cafeteria verified by POS register transaction and staff." },
        suspect_nigel: { eliminatedByEvidenceId: "ev_8_reception_cctv", reason: "Nigel was in the breaker closet; CCTV captured Damon carrying the blueprint cylinder." },
      },
      explanation:
        "Damon claimed he remained in the dry reception area, but his coat and boots were dripping with rainwater matching the muddy prints by the drafting table. CCTV caught him entering the fire stairwell and returning with the blueprint cylinder.",
    },
  },

  {
    id: "case_009",
    caseNumber: 9,
    title: "The Quantum Drive Disappearance",
    difficulty: "MEDIUM",
    summary: "An encrypted solid-state quantum drive was removed from the sub-zero containment pod during cleanroom maintenance.",
    scenario:
      "At 03:15 PM at Synapse Labs, the temperature-controlled Cryo-Chamber reported a weight discrepancy. The cryogenic quantum storage drive (weighing 450 grams) had been replaced with an identical dummy weight of lead.",
    investigationPoints: 10,
    scoring: {
      parDurationSec: 240,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_tariq",
        name: "Dr. Tariq Al-Mansoor",
        role: "Senior Cryogenics Scientist",
        bio: "Had direct access to the liquid nitrogen cooling controls.",
        initialStatement: "I was in the observation mezzanine watching the automated coolant purge from 03:00 to 03:20 PM.",
      },
      {
        id: "suspect_veronica",
        name: "Veronica Drake",
        role: "Sub-Zero Technician",
        bio: "Entered the cryo-chamber at 03:08 PM wearing a full insulated thermal suit.",
        initialStatement: "I only entered to replace the thermal pressure valve. I never touched the containment pod.",
      },
      {
        id: "suspect_simon",
        name: "Simon Vance",
        role: "Quality Inspector",
        bio: "Was reviewing the digital temperature telemetry from the external terminal.",
        initialStatement: "I was standing beside Dr. Tariq on the mezzanine reviewing digital logs.",
      },
    ],
    initialClues: [
      { id: "clue_9_1", text: "The dummy weight was placed inside the pod at 03:09 PM when the pod latch sensor opened for 30 seconds." },
      { id: "clue_9_2", text: "Entering the Cryo-Chamber requires passing through the airlock weight-scale." },
    ],
    evidence: [
      {
        id: "ev_9_airlock_scale",
        title: "Airlock Digital Weight Scale Log",
        description: "Airlock telemetry records Veronica entering at 03:08 PM with a total weight of 78.2 kg and exiting at 03:12 PM at 78.65 kg (+450 grams exactly matching the quantum drive in her thermal suit pocket).",
        type: "CONTRADICTION",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_veronica"],
        linkedTimelineEventIds: ["tl_9_2", "tl_9_3"],
      },
      {
        id: "ev_9_thermal_glove",
        title: "Thermal Glove Lead Residue Analysis",
        description: "Forensic swabs of Veronica's thermal gloves reveal traces of lead oxidation matching the dummy weight placed into the pod.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_veronica"],
        linkedTimelineEventIds: ["tl_9_2"],
      },
      {
        id: "ev_9_mezzanine_camera",
        title: "Observation Mezzanine Camera",
        description: "Camera footage confirms Dr. Tariq and Simon Vance stood together continuously in the mezzanine from 02:55 to 03:25 PM.",
        type: "CCTV",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_tariq", "suspect_simon"],
        linkedTimelineEventIds: ["tl_9_1", "tl_9_4"],
      },
    ],
    timeline: [
      { id: "tl_9_1", timeLabel: "03:00 PM", minuteOffset: 0, description: "Coolant purge begins; Dr. Tariq and Simon watch from mezzanine.", linkedSuspectIds: ["suspect_tariq", "suspect_simon"], isInitial: true },
      { id: "tl_9_2", timeLabel: "03:08 PM", minuteOffset: 8, description: "Veronica enters airlock and accesses pod with lead dummy weight.", linkedSuspectIds: ["suspect_veronica"], isInitial: false, unlockWithEvidenceId: "ev_9_airlock_scale" },
      { id: "tl_9_3", timeLabel: "03:12 PM", minuteOffset: 12, description: "Veronica exits airlock carrying additional 450 grams.", linkedSuspectIds: ["suspect_veronica"], isInitial: false, unlockWithEvidenceId: "ev_9_airlock_scale" },
      { id: "tl_9_4", timeLabel: "03:15 PM", minuteOffset: 15, description: "Cryo-chamber automated weight sensor triggers alert.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_veronica",
      culpritName: "Veronica Drake",
      requiredEvidenceIds: ["ev_9_airlock_scale", "ev_9_thermal_glove"],
      primaryContradictionEvidenceIds: ["ev_9_airlock_scale"],
      expectedTimelineOrder: ["tl_9_1", "tl_9_2", "tl_9_3", "tl_9_4"],
      eliminatedSuspects: {
        suspect_tariq: { eliminatedByEvidenceId: "ev_9_mezzanine_camera", reason: "Dr. Tariq was on the observation mezzanine on camera during the entire purge." },
        suspect_simon: { eliminatedByEvidenceId: "ev_9_mezzanine_camera", reason: "Simon was on the mezzanine beside Dr. Tariq throughout." },
      },
      explanation:
        "Veronica claimed she only replaced a pressure valve and never touched the pod. However, lead residue was found on her gloves and the airlock digital weight scale proved she weighed 450 grams more upon exiting than when entering.",
    },
  },

  // ==========================================
  // HARD CASES (3 Cases)
  // ==========================================
  {
    id: "case_010",
    caseNumber: 10,
    title: "The Connoisseur's Cipher",
    difficulty: "HARD",
    summary: "A priceless encrypted Da Vinci manuscript folio was stolen from the high-security subterranean vault of Sterling & Co.",
    scenario:
      "At 04:30 AM, the bi-weekly vault integrity check at Sterling Auction House discovered that Vault 7B had been breached. The double-combination rotary lock had been decoded and the 15th-century folio removed. The crime required dual-factor physical keys, knowledge of the cipher schedule, and bypassing motion beams during a scheduled 8-minute ventilation purge.",
    investigationPoints: 12,
    scoring: {
      parDurationSec: 300,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_gregory",
        name: "Gregory Vance",
        role: "Chief Vault Custodian",
        bio: "Holds Keycard A and manages vault rotation schedules.",
        initialStatement: "I was asleep in the guard annex on the ground floor from 03:00 to 05:00 AM. My Keycard A was locked in my biometric safe.",
      },
      {
        id: "suspect_beatrice_v",
        name: "Dr. Beatrice Vane",
        role: "Manuscript Authenticator",
        bio: "Holds Keycard B and decoded the cipher mechanism for display.",
        initialStatement: "I was at the airport hotel awaiting my 06:00 AM flight to Geneva.",
      },
      {
        id: "suspect_cedric",
        name: "Cedric Thorne",
        role: "Ventilation Contractor",
        bio: "Maintained the HVAC system and set the 04:10 AM purge schedule.",
        initialStatement: "I was in the rooftop HVAC room until 04:00 AM, then logged out at the parking gate at 04:05 AM.",
      },
      {
        id: "suspect_natalie",
        name: "Natalie Shaw",
        role: "Appraiser & Safe Specialist",
        bio: "Specialist who calibrated the acoustic sensors on Vault 7B.",
        initialStatement: "I was in the basement workshop calibrating laser sensors with my assistant until 04:45 AM.",
      },
    ],
    initialClues: [
      { id: "clue_10_1", text: "Vault 7B requires Keycard A and Keycard B swiped within 30 seconds of each other." },
      { id: "clue_10_2", text: "The motion beams inside Vault 7B were disabled exclusively during the ventilation purge between 04:10 AM and 04:18 AM." },
      { id: "clue_10_3", text: "A specialized glass-fiber glove thread was found snagged on the rotary lock dial." },
    ],
    evidence: [
      {
        id: "ev_10_parking_gate",
        title: "Parking Gate Automated License Plate Log",
        description: "Parking gate camera proves Cedric Thorne's van did NOT exit at 04:05 AM as claimed; his van remained in the underground loading dock until 04:22 AM.",
        type: "CONTRADICTION",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_cedric"],
        linkedTimelineEventIds: ["tl_10_2", "tl_10_3"],
      },
      {
        id: "ev_10_clone_device",
        title: "HVAC Duct Inspection & Cloned Badge Reader",
        description: "Inside the ventilation duct feeding Vault 7B, police discovered an electronic relay device and a cloned RFID transponder registered to Cedric Thorne that simulated Keycard A and B signals.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 4,
        linkedSuspectIds: ["suspect_cedric"],
        linkedTimelineEventIds: ["tl_10_2"],
      },
      {
        id: "ev_10_hotel_call",
        title: "Airport Hotel Front Desk & Keycard Logs",
        description: "Hotel logs verify Dr. Beatrice Vane checked in at 11:00 PM and her room door remained unbroken until checkout at 05:15 AM.",
        type: "ACCESS_LOG",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_beatrice_v"],
        linkedTimelineEventIds: ["tl_10_1"],
      },
      {
        id: "ev_10_natalie_assistant",
        title: "Assistant Sworn Deposition & Video",
        description: "Natalie's assistant and uninterrupted security cameras confirm Natalie was continuously visible in the workshop throughout the entire morning.",
        type: "STATEMENT",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_natalie"],
        linkedTimelineEventIds: ["tl_10_1", "tl_10_4"],
      },
    ],
    timeline: [
      { id: "tl_10_1", timeLabel: "03:45 AM", minuteOffset: 45, description: "Beatrice asleep in airport hotel; Natalie working in workshop.", linkedSuspectIds: ["suspect_beatrice_v", "suspect_natalie"], isInitial: true },
      { id: "tl_10_2", timeLabel: "04:10 AM", minuteOffset: 70, description: "Ventilation purge disables vault motion beams; cloned RFID relay triggers locks.", linkedSuspectIds: ["suspect_cedric"], isInitial: false, unlockWithEvidenceId: "ev_10_clone_device" },
      { id: "tl_10_3", timeLabel: "04:16 AM", minuteOffset: 76, description: "Folio removed; Cedric Thorne departs loading dock at 04:22 AM.", linkedSuspectIds: ["suspect_cedric"], isInitial: false, unlockWithEvidenceId: "ev_10_parking_gate" },
      { id: "tl_10_4", timeLabel: "04:30 AM", minuteOffset: 90, description: "Vault integrity patrol discovers Vault 7B open and empty.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_cedric",
      culpritName: "Cedric Thorne",
      requiredEvidenceIds: ["ev_10_parking_gate", "ev_10_clone_device"],
      primaryContradictionEvidenceIds: ["ev_10_parking_gate"],
      expectedTimelineOrder: ["tl_10_1", "tl_10_2", "tl_10_3", "tl_10_4"],
      eliminatedSuspects: {
        suspect_gregory: { eliminatedByEvidenceId: "ev_10_clone_device", reason: "Gregory's real keycard was not used; an electronic cloned device installed in the HVAC duct simulated the signal." },
        suspect_beatrice_v: { eliminatedByEvidenceId: "ev_10_hotel_call", reason: "Beatrice was at the airport hotel verified by room lock records." },
        suspect_natalie: { eliminatedByEvidenceId: "ev_10_natalie_assistant", reason: "Natalie was visible in the workshop with her assistant and security cameras." },
      },
      explanation:
        "Cedric Thorne timed the theft during his scheduled 04:10 AM ventilation purge when motion sensors were disabled. He lied about leaving at 04:05 AM (parking gate records show he stayed until 04:22 AM), and his electronic relay device was recovered inside the HVAC shaft.",
    },
  },

  {
    id: "case_011",
    caseNumber: 11,
    title: "The Manor of Whispers",
    difficulty: "HARD",
    summary: "Lord Ravenscroft's handwritten codicil was stolen from his locked study during an estate-wide storm blackout.",
    scenario:
      "At 10:15 PM during an isolated thunderstorm at Ravenscroft Manor, the main power failed for 12 minutes. At 10:30 PM, Lord Ravenscroft's locked study was found unlocked, and his revised handwritten will disinheriting his brother had been removed from the bureau.",
    investigationPoints: 12,
    scoring: {
      parDurationSec: 300,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_richard",
        name: "Richard Ravenscroft",
        role: "Estranged Brother",
        bio: "Was facing bankruptcy and stood to lose his estate inheritance under the new codicil.",
        initialStatement: "I was in the conservatory playing chess against myself by candlelight from 10:00 to 10:30 PM.",
      },
      {
        id: "suspect_eleanor",
        name: "Eleanor Vance",
        role: "Lord Ravenscroft's Private Nurse",
        bio: "Administered evening medicine at 09:45 PM.",
        initialStatement: "I was in the dispensary on the ground floor preparing tomorrow's medication trays.",
      },
      {
        id: "suspect_charles",
        name: "Charles Sterling",
        role: "Estate Groundskeeper",
        bio: "Responsible for starting the emergency generator in the courtyard shed.",
        initialStatement: "I ran out to the generator shed as soon as the power failed at 10:15 PM and remained there until lights came back at 10:27 PM.",
      },
      {
        id: "suspect_victoria",
        name: "Victoria Croft",
        role: "Daughter & Beneficiary",
        bio: "Advocated for the codicil to protect the estate heritage.",
        initialStatement: "I was in the library reading with Nurse Eleanor within earshot.",
      },
    ],
    initialClues: [
      { id: "clue_11_1", text: "The study window was unlatched from the inside, with wet mud tracks leading across the windowsill toward the garden trellis." },
      { id: "clue_11_2", text: "The generator shed log records automatic battery start, not a manual pull-cord start." },
    ],
    evidence: [
      {
        id: "ev_11_conservatory_candles",
        title: "Conservatory Candle & Wax Inspection",
        description: "The candles in the conservatory were completely unlit and cold with undisturbed cobwebs on the chess table, proving Richard was not in the conservatory as claimed.",
        type: "CONTRADICTION",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_richard"],
        linkedTimelineEventIds: ["tl_11_2"],
      },
      {
        id: "ev_11_garden_trellis",
        title: "Garden Trellis Mud & Fabric Snag",
        description: "On the garden trellis beneath the study window, investigators found a torn piece of velvet smoking jacket matching Richard's bespoke maroon jacket.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_richard"],
        linkedTimelineEventIds: ["tl_11_3"],
      },
      {
        id: "ev_11_charles_generator",
        title: "Generator Telemetry & Charles Witness",
        description: "Automatic generator computer logs confirm the backup generator fired automatically at 10:15 PM without manual intervention; Charles was seen in the staff kitchen by the cook.",
        type: "ACCESS_LOG",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_charles"],
        linkedTimelineEventIds: ["tl_11_2"],
      },
      {
        id: "ev_11_eleanor_dispensary",
        title: "Dispensary Digital Inventory Log",
        description: "Time-locked dispensary safe records confirm Eleanor logged 12 medication blister packs between 10:05 and 10:28 PM.",
        type: "STATEMENT",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_eleanor"],
        linkedTimelineEventIds: ["tl_11_1"],
      },
    ],
    timeline: [
      { id: "tl_11_1", timeLabel: "10:00 PM", minuteOffset: 0, description: "Estate quiet; Eleanor begins medication preparation in dispensary.", linkedSuspectIds: ["suspect_eleanor"], isInitial: true },
      { id: "tl_11_2", timeLabel: "10:15 PM", minuteOffset: 15, description: "Storm cuts main power; Richard climbs garden trellis to study window.", linkedSuspectIds: ["suspect_richard"], isInitial: false, unlockWithEvidenceId: "ev_11_conservatory_candles" },
      { id: "tl_11_3", timeLabel: "10:22 PM", minuteOffset: 22, description: "Codicil taken from bureau; Richard tears jacket escaping via trellis.", linkedSuspectIds: ["suspect_richard"], isInitial: false, unlockWithEvidenceId: "ev_11_garden_trellis" },
      { id: "tl_11_4", timeLabel: "10:30 PM", minuteOffset: 30, description: "Lord Ravenscroft discovers study door unlocked and codicil missing.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_richard",
      culpritName: "Richard Ravenscroft",
      requiredEvidenceIds: ["ev_11_conservatory_candles", "ev_11_garden_trellis"],
      primaryContradictionEvidenceIds: ["ev_11_conservatory_candles"],
      expectedTimelineOrder: ["tl_11_1", "tl_11_2", "tl_11_3", "tl_11_4"],
      eliminatedSuspects: {
        suspect_eleanor: { eliminatedByEvidenceId: "ev_11_eleanor_dispensary", reason: "Eleanor was in the time-locked dispensary logging medications." },
        suspect_charles: { eliminatedByEvidenceId: "ev_11_charles_generator", reason: "Charles was in the staff kitchen confirmed by the cook." },
        suspect_victoria: { eliminatedByEvidenceId: "ev_11_garden_trellis", reason: "Victoria was in the library and did not climb the garden trellis; the torn jacket belonged to Richard." },
      },
      explanation:
        "Richard claimed he was playing chess by candlelight in the conservatory, but the candles were unlit and cold. Under cover of the blackout, he climbed the garden trellis, unlatched the study window, and stole the codicil, tearing his maroon velvet smoking jacket on the trellis during his escape.",
    },
  },

  {
    id: "case_012",
    caseNumber: 12,
    title: "The Grandmaster's Gambit",
    difficulty: "HARD",
    summary: "The solid diamond-encrusted King piece from the World Chess Championship trophy was swapped with a cubic zirconia duplicate.",
    scenario:
      "At 06:00 PM following the closing ceremony of the World Chess Championship at the Grand Palace Hotel, the appraisal team detected that the 200-carat diamond King piece had been substituted with an identical replica. The trophy had been guarded in the Green Room under dual-custody protocols between 04:30 PM and 05:45 PM.",
    investigationPoints: 12,
    scoring: {
      parDurationSec: 300,
      maxScore: 100,
    },
    suspects: [
      {
        id: "suspect_viktor_k",
        name: "Viktor Korchnoi",
        role: "Championship Runner-Up",
        bio: "Grandmaster who lost the final match in a controversial tiebreaker.",
        initialStatement: "I was in my private suite #402 reviewing game recordings from 04:45 to 05:45 PM.",
      },
      {
        id: "suspect_sergei",
        name: "Sergei Orlov",
        role: "Official Trophy Custodian",
        bio: "Had the master briefcase containing the jewel velvet showcase.",
        initialStatement: "I remained inside the Green Room with Arbiter Vance the entire duration without leaving.",
      },
      {
        id: "suspect_helena",
        name: "Helena Rostova",
        role: "Chief Arbiter",
        bio: "Supervised the match and held the secondary lock code.",
        initialStatement: "I stepped out to the lobby for 5 minutes at 05:10 PM to answer a call from the federation.",
      },
      {
        id: "suspect_dmitri",
        name: "Dmitri Volkov",
        role: "Master Jeweler & Appraiser",
        bio: "Crafted the replica piece originally intended for promotional photography.",
        initialStatement: "I was at the hotel lounge with journalists displaying the brass tournament medals.",
      },
    ],
    initialClues: [
      { id: "clue_12_1", text: "The substitution required knowing the micro-latch opening sequence on the trophy base." },
      { id: "clue_12_2", text: "The replica piece had a density difference of 0.8 grams, detectable only by precision balance." },
      { id: "clue_12_3", text: "The Green Room has a 5-minute surveillance blind spot during the 05:10 PM guard rotation." },
    ],
    evidence: [
      {
        id: "ev_12_greenroom_log",
        title: "Green Room Entrance Badge Audit",
        description: "Electronic lock audit reveals Sergei Orlov was NOT alone in the Green Room; Viktor Korchnoi's VIP card swiped the door at 05:11 PM during Helena's 5-minute phone call.",
        type: "CONTRADICTION",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_viktor_k", "suspect_sergei"],
        linkedTimelineEventIds: ["tl_12_2"],
      },
      {
        id: "ev_12_suite_cctv",
        title: "4th Floor Suite 402 Corridor CCTV",
        description: "4th-floor hallway camera shows Viktor Korchnoi leaving his suite at 05:05 PM carrying a velvet jeweler pouch and returning at 05:22 PM.",
        type: "CCTV",
        unlockCost: 3,
        linkedSuspectIds: ["suspect_viktor_k"],
        linkedTimelineEventIds: ["tl_12_1", "tl_12_3"],
      },
      {
        id: "ev_12_diamond_tester",
        title: "Viktor's Luggage Thermal Conductivity Test",
        description: "Police search of Viktor Korchnoi's carry-on luggage recovered the genuine diamond King wrapped in a tournament score sheet with his signature.",
        type: "PHYSICAL_EVIDENCE",
        unlockCost: 4,
        linkedSuspectIds: ["suspect_viktor_k"],
        linkedTimelineEventIds: ["tl_12_3"],
      },
      {
        id: "ev_12_dmitri_lounge",
        title: "Journalist Press Photographs",
        description: "Timestamped press photos show Dmitri Volkov surrounded by 10 sports journalists continuously in the lobby lounge from 04:45 to 05:40 PM.",
        type: "STATEMENT",
        unlockCost: 2,
        linkedSuspectIds: ["suspect_dmitri"],
        linkedTimelineEventIds: ["tl_12_1", "tl_12_4"],
      },
    ],
    timeline: [
      { id: "tl_12_1", timeLabel: "04:45 PM", minuteOffset: 45, description: "Closing ceremony concludes; trophy placed in Green Room; Dmitri in lounge.", linkedSuspectIds: ["suspect_dmitri"], isInitial: true },
      { id: "tl_12_2", timeLabel: "05:10 PM", minuteOffset: 70, description: "Chief Arbiter steps out for phone call; Viktor Korchnoi enters Green Room.", linkedSuspectIds: ["suspect_viktor_k"], isInitial: false, unlockWithEvidenceId: "ev_12_greenroom_log" },
      { id: "tl_12_3", timeLabel: "05:18 PM", minuteOffset: 78, description: "Diamond piece substituted with replica; Viktor returns to Suite 402.", linkedSuspectIds: ["suspect_viktor_k"], isInitial: false, unlockWithEvidenceId: "ev_12_suite_cctv" },
      { id: "tl_12_4", timeLabel: "06:00 PM", minuteOffset: 120, description: "Appraisal team discovers diamond King replaced with replica.", linkedSuspectIds: [], isInitial: true },
    ],
    solution: {
      culpritId: "suspect_viktor_k",
      culpritName: "Viktor Korchnoi",
      requiredEvidenceIds: ["ev_12_greenroom_log", "ev_12_suite_cctv", "ev_12_diamond_tester"],
      primaryContradictionEvidenceIds: ["ev_12_greenroom_log", "ev_12_suite_cctv"],
      expectedTimelineOrder: ["tl_12_1", "tl_12_2", "tl_12_3", "tl_12_4"],
      eliminatedSuspects: {
        suspect_dmitri: { eliminatedByEvidenceId: "ev_12_dmitri_lounge", reason: "Dmitri was surrounded by journalists on camera throughout the window." },
        suspect_helena: { eliminatedByEvidenceId: "ev_12_diamond_tester", reason: "Helena was on the phone in the lobby; the real diamond King was discovered in Viktor's luggage." },
        suspect_sergei: { eliminatedByEvidenceId: "ev_12_suite_cctv", reason: "Sergei was distracted at his desk; Viktor entered and performed the physical swap." },
      },
      explanation:
        "Viktor Korchnoi claimed he remained in Suite 402 studying games, but corridor CCTV showed him leaving at 05:05 PM. When the Arbiter stepped out at 05:10 PM, Viktor entered the Green Room, executed the swap, and the authentic 200-carat diamond King was discovered hidden in his luggage wrapped in his signed score sheet.",
    },
  },
];
