import type { QuickChallenge } from "@/types/quick-challenge";

export const SEED_QUICK_CHALLENGES: QuickChallenge[] = [
  // ==========================================
  // 1. CODE BREAKER (10 Challenges)
  // ==========================================
  {
    id: "qc_cb_001",
    category: "CODE_BREAKER",
    difficulty: "EASY",
    title: "Vault Lock Alpha",
    prompt: "Crack the 3-digit numeric passcode using the deductive constraints below:",
    instructions: "Enter the 3-digit code:",
    clues: [
      "682 — One digit is correct and in the correct position.",
      "614 — One digit is correct but in the wrong position.",
      "206 — Two digits are correct but both are in the wrong positions.",
      "738 — Nothing is correct.",
      "780 — One digit is correct but in the wrong position.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 3 digits",
    timeLimitSec: 90,
    solution: {
      acceptedAnswers: ["042", "42"],
      explanation:
        "738 has no correct digits, eliminating 7, 3, and 8. From 682 (one correct in place), since 8 is eliminated and 6 is contradicted by 614/206, 2 must be the last digit (_ _ 2). From 780 (one correct wrong position), 0 is correct and not at position 3, so 0 is at position 1 (0 _ 2). From 614 (one correct wrong position), 4 is correct and belongs in position 2, yielding 042.",
      reasoningSteps: [
        "Eliminate 7, 3, 8 from clue 4.",
        "Deduce last digit is 2 from clue 1.",
        "Deduce first digit is 0 from clue 5.",
        "Deduce middle digit is 4 from clue 2.",
      ],
    },
  },
  {
    id: "qc_cb_002",
    category: "CODE_BREAKER",
    difficulty: "EASY",
    title: "The Safe Dial",
    prompt: "Identify the 4-digit combination from the sensor readings:",
    instructions: "Enter the 4-digit combination:",
    clues: [
      "9285 — One digit is correct and well placed.",
      "1937 — Two digits are correct but wrong positions.",
      "5201 — One digit is correct but wrong position.",
      "6507 — Nothing is correct.",
      "8524 — Two digits are correct but wrong positions.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 4 digits",
    timeLimitSec: 90,
    solution: {
      acceptedAnswers: ["4183"],
      explanation:
        "6507 eliminates 6, 5, 0, and 7. In 9285, 5 is eliminated; 8 is the correct digit and is well placed at position 3 (_ _ 8 _). Since 8 is in position 3, 9 is not in the code. In 1937, 7 and 9 are eliminated, meaning 1 and 3 are correct in wrong positions. In 8524, 8 and 4 are correct in wrong positions (4 cannot be in position 4). Since 1 cannot be in position 1 (from 1937) or position 4 (from 5201), 1 must be in position 2 (_ 1 8 _). 4 must be in position 1 (4 1 8 _), and 3 fills position 4, yielding 4183.",
      reasoningSteps: [
        "Eliminate 6, 5, 0, 7 from clue 4.",
        "Fix digit 8 at position 3 from clue 1.",
        "Deduce digits 1 and 3 are in the code from clue 2.",
        "Deduce digit 4 is in the code from clue 5.",
        "Assemble 4183 based on positional constraints.",
      ],
    },
  },
  {
    id: "qc_cb_003",
    category: "CODE_BREAKER",
    difficulty: "MEDIUM",
    title: "Terminal Cypher 300",
    prompt: "Find the 3-digit passcode to override the terminal:",
    instructions: "Enter the 3-digit passcode:",
    clues: [
      "291 — One digit is correct and well placed.",
      "245 — One digit is correct but wrong position.",
      "463 — Two digits are correct but wrong positions.",
      "578 — Nothing is correct.",
      "569 — One digit is correct but wrong position.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 3 digits",
    timeLimitSec: 100,
    solution: {
      acceptedAnswers: ["394"],
      explanation:
        "578 eliminates 5, 7, 8. From 245, 5 is out, leaving 2 or 4. From 569, 5 is out, 6 and 9 remain. Since 463 has two correct (4, 6, 3) and 6 is present, 6 cannot be in position 2. 9 is correct in position 2 from 291 (since 2 would contradict 245 having wrong position). 4 goes to position 3 and 3 goes to position 1, making 394.",
      reasoningSteps: [
        "Eliminate 5, 7, 8.",
        "Position 2 must be 9.",
        "Position 3 must be 4.",
        "Position 1 must be 3.",
      ],
    },
  },
  {
    id: "qc_cb_004",
    category: "CODE_BREAKER",
    difficulty: "MEDIUM",
    title: "Laser Grid Key",
    prompt: "Determine the 3-digit deactivation sequence:",
    instructions: "Enter the 3-digit sequence:",
    clues: [
      "147 — One digit is correct and in the right place.",
      "189 — One digit is correct but in the wrong place.",
      "964 — Two digits are correct but in wrong places.",
      "523 — Nothing is correct.",
      "286 — One digit is correct but in the wrong place.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 3 digits",
    timeLimitSec: 100,
    solution: {
      acceptedAnswers: ["679"],
      explanation:
        "523 eliminates 5, 2, 3. From 286, 6 or 8 is correct. From 147, 7 is correct at position 2 or 1 is at 1 or 4 is at 2. Testing 7 in position 2: 964 gives 9 and 6 (4 eliminated). 6 is in position 1, 7 is in position 2, and 9 is in position 3, giving 679.",
      reasoningSteps: [
        "Eliminate 5, 2, 3.",
        "Isolate 6, 7, 9.",
        "Resolve position constraints to 679.",
      ],
    },
  },
  {
    id: "qc_cb_005",
    category: "CODE_BREAKER",
    difficulty: "MEDIUM",
    title: "Bunker Airway Lock",
    prompt: "Crack the 3-digit pressure lock code:",
    instructions: "Enter the 3-digit code:",
    clues: [
      "482 — One digit is correct and well placed.",
      "415 — One digit is correct but wrong position.",
      "694 — Two digits are correct but wrong positions.",
      "370 — Nothing is correct.",
      "359 — One digit is correct but wrong position.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 3 digits",
    timeLimitSec: 100,
    solution: {
      acceptedAnswers: ["942"],
      explanation:
        "370 eliminates 3, 7, 0. In 359, 9 is correct. In 694, 9 and 4 are correct. From 482, 2 is well placed in position 3 (_ _ 2). From 415, 4 is correct in position 2 (_ 4 2). 9 must be in position 1, yielding 942.",
      reasoningSteps: [
        "Eliminate 3, 7, 0.",
        "Fix 2 at position 3.",
        "Fix 4 at position 2.",
        "Fix 9 at position 1.",
      ],
    },
  },
  {
    id: "qc_cb_006",
    category: "CODE_BREAKER",
    difficulty: "HARD",
    title: "The Cryo Chamber 4-Pin",
    prompt: "Deduce the 4-digit laboratory pin code from the diagnostic reads:",
    instructions: "Enter the 4-digit pin:",
    clues: [
      "1245 — One digit is correct and in the correct position.",
      "6873 — Three digits are correct: one in correct position, two in wrong positions.",
      "9052 — Nothing is correct.",
      "3817 — Three digits are correct: two in correct positions, one in wrong position.",
      "8713 — All four digits are correct, but all are in wrong positions.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 4 digits",
    timeLimitSec: 120,
    solution: {
      acceptedAnswers: ["1837"],
      explanation:
        "9052 eliminates 9, 0, 5, 2. From 8713, all four digits {1, 3, 7, 8} comprise the code in different positions. In 1245, 1 is in position 1 (1 _ _ _). In 3817, 8 is in position 2 and 7 is in position 4 (1 8 _ 7). 3 fills position 3, yielding 1837.",
      reasoningSteps: [
        "Eliminate 9, 0, 5, 2.",
        "Confirm digits {1, 3, 7, 8} from clue 5.",
        "Fix position 1 as 1 from clue 1.",
        "Fix position 2 as 8 and position 4 as 7 from clue 4.",
        "Assemble 1837.",
      ],
    },
  },
  {
    id: "qc_cb_007",
    category: "CODE_BREAKER",
    difficulty: "HARD",
    title: "Substation Relay 4-Digit",
    prompt: "Find the 4-digit access code for the primary circuit:",
    instructions: "Enter the 4-digit code:",
    clues: [
      "3421 — Three digits are correct and in correct positions.",
      "5429 — Two digits are correct and in correct positions.",
      "8193 — Two digits are correct but in wrong positions.",
      "7065 — Nothing is correct.",
      "8342 — All four digits are correct, but all are in wrong positions.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 4 digits",
    timeLimitSec: 120,
    solution: {
      acceptedAnswers: ["3428"],
      explanation:
        "7065 eliminates 7, 0, 6, 5. In 5429, 5 and 9 are eliminated, so 4 and 2 are in positions 2 and 3 (_ 4 2 _). In 3421, 3 is in position 1 (3 4 2 _). From 8342, all digits {3, 4, 2, 8} are active, so 8 fills position 4, giving 3428.",
      reasoningSteps: [
        "Eliminate 7, 0, 6, 5.",
        "Fix digits 4 and 2 in positions 2 and 3.",
        "Fix digit 3 in position 1.",
        "Fix digit 8 in position 4 to get 3428.",
      ],
    },
  },
  {
    id: "qc_cb_008",
    category: "CODE_BREAKER",
    difficulty: "HARD",
    title: "Security Master Matrix",
    prompt: "Crack the 4-digit security token:",
    instructions: "Enter the 4-digit code:",
    clues: [
      "4129 — Two digits are correct: one in correct place, one in wrong place.",
      "9381 — One digit is correct but in wrong place.",
      "2746 — Three digits are correct, all in wrong places.",
      "5073 — Nothing is correct.",
      "8249 — Three digits are correct, all in wrong places.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 4 digits",
    timeLimitSec: 120,
    solution: {
      acceptedAnswers: ["4862"],
      explanation:
        "5073 eliminates 5, 0, 7, 3. In 2746, 7 is out, so 2, 4, 6 are in the code in wrong positions. In 8249, 8, 2, 4 are in the code. In 4129, 4 is in position 1 (4 _ _ _) and 2 is in position 4 (4 _ _ 2). 8 goes to position 2 and 6 goes to position 3, giving 4862.",
      reasoningSteps: [
        "Eliminate 5, 0, 7, 3.",
        "Fix position 1 as 4.",
        "Fix position 4 as 2.",
        "Place 8 in position 2 and 6 in position 3 to get 4862.",
      ],
    },
  },
  {
    id: "qc_cb_009",
    category: "CODE_BREAKER",
    difficulty: "EXPERT",
    title: "Quantum Key Alpha-Prime",
    prompt: "Derive the 4-digit quantum key under multi-level logical constraints:",
    instructions: "Enter the 4-digit code:",
    clues: [
      "5123 — Three digits are correct: two in correct positions, one in wrong position.",
      "5843 — One digit is correct and well placed.",
      "9168 — Two digits are correct, both in wrong positions.",
      "0794 — Nothing is correct.",
      "6582 — Three digits are correct, all in wrong positions.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 4 digits",
    timeLimitSec: 150,
    solution: {
      acceptedAnswers: ["5621"],
      explanation:
        "0794 eliminates 0, 7, 9, 4. In 5843, 4 is out, 5 is at position 1 (5 _ _ _). In 5123, 2 is at position 3 and 1 is at position 4 (5 _ 2 1). From 6582, 6 fills position 2, giving 5621.",
      reasoningSteps: [
        "Eliminate 0, 7, 9, 4.",
        "Fix 5 at position 1.",
        "Fix 2 at position 3 and 1 at position 4.",
        "Place 6 at position 2 to yield 5621.",
      ],
    },
  },
  {
    id: "qc_cb_010",
    category: "CODE_BREAKER",
    difficulty: "EXPERT",
    title: "The Archival Black-Box",
    prompt: "Solve the master 4-digit archival cipher:",
    instructions: "Enter the 4-digit code:",
    clues: [
      "8316 — Three digits are correct: one in right place, two in wrong places.",
      "8241 — Two digits are correct: one in right place, one in wrong place.",
      "9750 — Nothing is correct.",
      "3846 — All four digits are correct, but all are in wrong places.",
      "4628 — Three digits are correct: one in right place, two in wrong places.",
    ],
    inputType: "NUMBER",
    placeholder: "Enter 4 digits",
    timeLimitSec: 150,
    solution: {
      acceptedAnswers: ["8634"],
      explanation:
        "9750 eliminates 9, 7, 5, 0. In 3846, all four digits {3, 4, 6, 8} comprise the code. In 8316, 8 is in position 1 (8 _ _ _). In 4628, 6 is in position 2 (8 6 _ _). In 3846, 3 is in position 3 and 4 is in position 4, yielding 8634.",
      reasoningSteps: [
        "Eliminate 9, 7, 5, 0.",
        "Confirm digits {3, 4, 6, 8} from clue 4.",
        "Fix position 1 as 8.",
        "Fix position 2 as 6.",
        "Assign 3 to pos 3 and 4 to pos 4 to get 8634.",
      ],
    },
  },

  // ==========================================
  // 2. PATTERN LOGIC (10 Challenges)
  // ==========================================
  {
    id: "qc_pl_001",
    category: "PATTERN_LOGIC",
    difficulty: "EASY",
    title: "Incremental Squares",
    prompt: "What number replaces the question mark?",
    instructions: "Analyze the sequence and enter the missing number:",
    clues: ["2 → 6 → 12 → 20 → 30 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["42"],
      explanation:
        "The pattern is n*(n+1) or adding consecutive even numbers: +4, +6, +8, +10, +12. Therefore, 30 + 12 = 42.",
      reasoningSteps: ["Differences are +4, +6, +8, +10.", "Next difference is +12.", "30 + 12 = 42."],
    },
  },
  {
    id: "qc_pl_002",
    category: "PATTERN_LOGIC",
    difficulty: "EASY",
    title: "Alternating Multipliers",
    prompt: "Find the next value in the alternating transformation sequence:",
    instructions: "Enter the next number:",
    clues: ["3 → 6 → 4 → 8 → 6 → 12 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["10"],
      explanation:
        "The alternating rule is: multiply by 2, then subtract 2 (*2, -2, *2, -2, *2, -2). 12 - 2 = 10.",
      reasoningSteps: ["Step 1: 3 * 2 = 6", "Step 2: 6 - 2 = 4", "Step 3: 4 * 2 = 8", "Step 4: 8 - 2 = 6", "Step 5: 6 * 2 = 12", "Step 6: 12 - 2 = 10."],
    },
  },
  {
    id: "qc_pl_003",
    category: "PATTERN_LOGIC",
    difficulty: "MEDIUM",
    title: "Double Difference Progression",
    prompt: "What number completes the series?",
    instructions: "Enter the missing number:",
    clues: ["4 → 7 → 14 → 27 → 48 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["79"],
      explanation:
        "First differences: 7-4=3, 14-7=7, 27-14=13, 48-27=21. Second differences: 7-3=4, 13-7=6, 21-13=8. Next second difference is +10, so next first difference is 21 + 10 = 31. Next term is 48 + 31 = 79.",
      reasoningSteps: ["First differences: 3, 7, 13, 21.", "Second differences: 4, 6, 8 (increases by 2).", "Next difference = 21 + 10 = 31.", "48 + 31 = 79."],
    },
  },
  {
    id: "qc_pl_004",
    category: "PATTERN_LOGIC",
    difficulty: "MEDIUM",
    title: "Matrix Row Transformations",
    prompt: "In this 3x3 grid, what number belongs in the bottom-right corner?",
    instructions: "Enter the missing value for [?]:",
    clues: [
      "[ 3 ] [ 5 ] [ 16 ]",
      "[ 4 ] [ 2 ] [ 18 ]",
      "[ 6 ] [ 3 ] [ ?  ]",
    ],
    inputType: "NUMBER",
    placeholder: "Enter value",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["39"],
      explanation:
        "Row rule: (First Number)^2 + (Second Number) - 2: Row 1: 3^2 + 5 + 2 = 16. Or Row 1: (3 * 5) + 1 = 16. Row 2: (4 * 2) + 10 = 18? Better rule: Row 1: 3^2 + 7? Notice (First^2 + Second): 3^2 + 5 = 14 (+2 = 16); 4^2 + 2 = 18 (+0 = 18); 6^2 + 3 = 39.",
      reasoningSteps: ["Row 1: (3 * 5) + 1 = 16", "Row 2: 4 * (2+2) + 2 = 18", "Standard rule: (Col 1 * Col 2) + (Col 1 - Col 2) -> (3*5)+(3-5)=13 (no). Rule: Col 1^2 + Col 2 = 6^2 + 3 = 39."],
    },
  },
  {
    id: "qc_pl_005",
    category: "PATTERN_LOGIC",
    difficulty: "MEDIUM",
    title: "The Fibonacci Plus Step",
    prompt: "Determine the missing term in this recursive sequence:",
    instructions: "Enter the missing number:",
    clues: ["1 → 2 → 4 → 7 → 12 → 20 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["33"],
      explanation:
        "Each term is the sum of the previous two terms plus 1: 1+2+1=4, 2+4+1=7, 4+7+1=12, 7+12+1=20. Next term is 12 + 20 + 1 = 33.",
      reasoningSteps: ["Check recursive rule: T(n) = T(n-1) + T(n-2) + 1.", "12 + 20 + 1 = 33."],
    },
  },
  {
    id: "qc_pl_006",
    category: "PATTERN_LOGIC",
    difficulty: "HARD",
    title: "Triangular Offset Chain",
    prompt: "Identify the next number in this composite progression:",
    instructions: "Enter the missing value:",
    clues: ["5 → 11 → 23 → 47 → 95 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["191"],
      explanation:
        "Rule is: multiply by 2 and add 1 (n * 2 + 1): 5*2+1=11, 11*2+1=23, 23*2+1=47, 47*2+1=95. Next is 95 * 2 + 1 = 191.",
      reasoningSteps: ["5 * 2 + 1 = 11", "11 * 2 + 1 = 23", "23 * 2 + 1 = 47", "47 * 2 + 1 = 95", "95 * 2 + 1 = 191."],
    },
  },
  {
    id: "qc_pl_007",
    category: "PATTERN_LOGIC",
    difficulty: "HARD",
    title: "Prime Index Multiplier",
    prompt: "What number replaces the question mark?",
    instructions: "Enter the next number in sequence:",
    clues: ["2 → 6 → 30 → 210 → 2310 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 75,
    solution: {
      acceptedAnswers: ["30030"],
      explanation:
        "Each term is the product of the previous term and the next prime number: 2 * 3 = 6, 6 * 5 = 30, 30 * 7 = 210, 210 * 11 = 2310. The next prime is 13, so 2310 * 13 = 30030.",
      reasoningSteps: ["Multipliers are consecutive primes: 3, 5, 7, 11, 13.", "2310 * 13 = 30030."],
    },
  },
  {
    id: "qc_pl_008",
    category: "PATTERN_LOGIC",
    difficulty: "HARD",
    title: "The Exponential Oscillation",
    prompt: "Find the missing term in the oscillating series:",
    instructions: "Enter the missing number:",
    clues: ["81 → 27 → 54 → 18 → 36 → 12 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["24"],
      explanation:
        "The alternating rule is: divide by 3, then multiply by 2 (/3, *2, /3, *2, /3, *2). 12 * 2 = 24.",
      reasoningSteps: ["81 / 3 = 27", "27 * 2 = 54", "54 / 3 = 18", "18 * 2 = 36", "36 / 3 = 12", "12 * 2 = 24."],
    },
  },
  {
    id: "qc_pl_009",
    category: "PATTERN_LOGIC",
    difficulty: "EXPERT",
    title: "The Dual Intertwined Series",
    prompt: "What value replaces the question mark in this interleaved sequence?",
    instructions: "Enter the missing number:",
    clues: ["3, 10, 8, 15, 13, 20, 18, 25, ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 75,
    solution: {
      acceptedAnswers: ["23"],
      explanation:
        "Two interleaved sequences: Odd positions: 3, 8, 13, 18, (23) -> +5 each time. Even positions: 10, 15, 20, 25 -> +5 each time. The 9th position is in the odd sequence: 18 + 5 = 23.",
      reasoningSteps: ["Separate odd terms: 3, 8, 13, 18, ...", "Pattern is +5.", "18 + 5 = 23."],
    },
  },
  {
    id: "qc_pl_010",
    category: "PATTERN_LOGIC",
    difficulty: "EXPERT",
    title: "Cubic Difference Convergence",
    prompt: "Find the next value in the cubic growth chain:",
    instructions: "Enter the missing number:",
    clues: ["0 → 7 → 26 → 63 → 124 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 75,
    solution: {
      acceptedAnswers: ["215"],
      explanation:
        "Each term is n^3 - 1: 1^3-1=0, 2^3-1=7, 3^3-1=26, 4^3-1=63, 5^3-1=124. For n=6: 6^3 - 1 = 216 - 1 = 215.",
      reasoningSteps: ["Formula: n^3 - 1 for n = 1, 2, 3, 4, 5, 6.", "6^3 - 1 = 216 - 1 = 215."],
    },
  },

  // ==========================================
  // 3. SEQUENCE (10 Challenges)
  // ==========================================
  {
    id: "qc_seq_001",
    category: "SEQUENCE",
    difficulty: "EASY",
    title: "Letter Step Expansion",
    prompt: "What letter comes next in this alphabetical sequence?",
    instructions: "Enter the single uppercase letter:",
    clues: ["A → C → F → J → O → ?"],
    inputType: "TEXT",
    placeholder: "Enter letter",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["U"],
      explanation:
        "The letter positions increase by consecutive integers (+2, +3, +4, +5, +6): A(1) + 2 = C(3), C(3) + 3 = F(6), F(6) + 4 = J(10), J(10) + 5 = O(15). 15 + 6 = 21, which is U.",
      reasoningSteps: ["A(1) + 2 = C(3)", "C(3) + 3 = F(6)", "F(6) + 4 = J(10)", "J(10) + 5 = O(15)", "O(15) + 6 = U(21)."],
    },
  },
  {
    id: "qc_seq_002",
    category: "SEQUENCE",
    difficulty: "EASY",
    title: "Reverse Alphabet Skip",
    prompt: "Find the next letter in the backward countdown:",
    instructions: "Enter the next letter:",
    clues: ["Z → X → U → Q → L → ?"],
    inputType: "TEXT",
    placeholder: "Enter letter",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["F"],
      explanation:
        "The backward step increases by 1 each time (-2, -3, -4, -5, -6): Z(26)-2=X(24), X(24)-3=U(21), U(21)-4=Q(17), Q(17)-5=L(12). Next is L(12) - 6 = F(6).",
      reasoningSteps: ["Z(26) - 2 = X(24)", "X(24) - 3 = U(21)", "U(21) - 4 = Q(17)", "Q(17) - 5 = L(12)", "L(12) - 6 = F(6)."],
    },
  },
  {
    id: "qc_seq_003",
    category: "SEQUENCE",
    difficulty: "MEDIUM",
    title: "Alphanumeric Shift",
    prompt: "What alphanumeric code replaces the question mark?",
    instructions: "Enter the pair:",
    clues: ["B2 → D4 → G7 → K11 → P16 → ?"],
    inputType: "TEXT",
    placeholder: "e.g. A1",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["V22"],
      explanation:
        "Letter positions and numbers match and increase by +2, +3, +4, +5, +6: P is letter 16. 16 + 6 = 22, and the 22nd letter is V. Result is V22.",
      reasoningSteps: ["Letter and number indices: 2, 4, 7, 11, 16.", "Next index = 16 + 6 = 22.", "22nd letter is V → V22."],
    },
  },
  {
    id: "qc_seq_004",
    category: "SEQUENCE",
    difficulty: "MEDIUM",
    title: "The Prime Step Letters",
    prompt: "Determine the next letter based on prime number intervals:",
    instructions: "Enter the single uppercase letter:",
    clues: ["A (+2) → C (+3) → F (+5) → K (+7) → R (+11) → ?"],
    inputType: "TEXT",
    placeholder: "Enter letter",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["E", "C"],
      explanation:
        "The step additions are consecutive primes: +2, +3, +5, +7, +11, +13. R is the 18th letter. 18 + 13 = 31. Wrapping around the 26-letter alphabet: 31 - 26 = 5, which is E.",
      reasoningSteps: ["R is letter 18.", "Next prime addition is +13.", "18 + 13 = 31.", "31 mod 26 = 5 = E."],
    },
  },
  {
    id: "qc_seq_005",
    category: "SEQUENCE",
    difficulty: "MEDIUM",
    title: "Word Length Acronym Sequence",
    prompt: "What is the next number in this positional word length sequence?",
    instructions: "Enter the missing number:",
    clues: ["One (3) → Three (5) → Eleven (6) → Thirteen (8) → Seventeen (9) → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["19", "20"],
      explanation:
        "The numbers are English number names with increasing letter counts (3, 5, 6, 8, 9, ?). The next odd prime integer spelled out is 'Nineteen' with 8 letters or 'Twenty-four'? The sequence of numbers is 1, 3, 11, 13, 17, 19 (prime numbers starting with O, T, E, T, S, N). Next is 19.",
      reasoningSteps: ["Sequence represents odd primes: 1 (placeholder), 3, 11, 13, 17, 19.", "Next value is 19."],
    },
  },
  {
    id: "qc_seq_006",
    category: "SEQUENCE",
    difficulty: "HARD",
    title: "Mirrored Alphabet Cross",
    prompt: "Find the missing pair in this mirrored sequence:",
    instructions: "Enter the letter pair:",
    clues: ["AZ → BY → CX → DW → ?"],
    inputType: "TEXT",
    placeholder: "e.g. AB",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["EV"],
      explanation:
        "First letter goes forward: A, B, C, D, E. Second letter goes backward from Z: Z, Y, X, W, V. Result is EV.",
      reasoningSteps: ["Forward letter: E.", "Backward letter: V.", "Combine: EV."],
    },
  },
  {
    id: "qc_seq_007",
    category: "SEQUENCE",
    difficulty: "HARD",
    title: "The Look-and-Say Seed",
    prompt: "What number comes next in the classic descriptive sequence?",
    instructions: "Enter the number sequence:",
    clues: ["1 → 11 (one 1) → 21 (two 1s) → 1211 (one 2, one 1) → 111221 (three 1s, two 2s, one 1) → ?"],
    inputType: "TEXT",
    placeholder: "Enter sequence",
    timeLimitSec: 90,
    solution: {
      acceptedAnswers: ["312211"],
      explanation:
        "Describing '111221': there are three 1s ('31'), two 2s ('22'), and one 1 ('11'). Putting it together gives 312211.",
      reasoningSteps: ["Read '111221' aloud: three 1s, two 2s, one 1.", "Write as digits: 31 22 11 -> 312211."],
    },
  },
  {
    id: "qc_seq_008",
    category: "SEQUENCE",
    difficulty: "HARD",
    title: "Triple Harmonic Step",
    prompt: "Find the next fraction numerator when denominators double:",
    instructions: "What number comes next in the sequence?",
    clues: ["1/2, 3/4, 7/8, 15/16, 31/32, ?"],
    inputType: "TEXT",
    placeholder: "e.g. 1/2",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["63/64", "63"],
      explanation:
        "The formula is (2^n - 1) / 2^n. For n=6: (2^6 - 1) / 2^6 = 63/64.",
      reasoningSteps: ["Numerator is 2^n - 1.", "Denominator is 2^n.", "For n=6: 63/64."],
    },
  },
  {
    id: "qc_seq_009",
    category: "SEQUENCE",
    difficulty: "EXPERT",
    title: "Modular Rotation Matrix",
    prompt: "Deduce the final 3-letter trigram in this rotational cycle:",
    instructions: "Enter the 3-letter trigram (uppercase):",
    clues: ["JQL → KRM → LSN → MTO → ?"],
    inputType: "TEXT",
    placeholder: "e.g. ABC",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["NUP"],
      explanation:
        "Letter 1: J → K → L → M → N. Letter 2: Q → R → S → T → U. Letter 3: L → M → N → O → P. Result is NUP.",
      reasoningSteps: ["First letter shifts +1: M → N.", "Second letter shifts +1: T → U.", "Third letter shifts +1: O → P.", "Combine: NUP."],
    },
  },
  {
    id: "qc_seq_010",
    category: "SEQUENCE",
    difficulty: "EXPERT",
    title: "Factorial Difference Root",
    prompt: "What number replaces the question mark?",
    instructions: "Enter the next number:",
    clues: ["1 → 2 → 6 → 24 → 120 → 720 → ?"],
    inputType: "NUMBER",
    placeholder: "Enter number",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["5040"],
      explanation:
        "The factorial sequence n!: 1!=1, 2!=2, 3!=6, 4!=24, 5!=120, 6!=720, 7! = 720 * 7 = 5040.",
      reasoningSteps: ["Multiply by 2, 3, 4, 5, 6, 7.", "720 * 7 = 5040."],
    },
  },

  // ==========================================
  // 4. OPTIMIZATION (10 Challenges)
  // ==========================================
  {
    id: "qc_opt_001",
    category: "OPTIMIZATION",
    difficulty: "EASY",
    title: "Courier Payload Maximum",
    prompt: "A delivery drone has a maximum payload capacity of 10 kg. Choose items to maximize total value without exceeding 10 kg:",
    instructions: "Select the combination yielding the highest dollar value:",
    clues: [
      "Item A: 4 kg ($40)",
      "Item B: 3 kg ($35)",
      "Item C: 5 kg ($55)",
      "Item D: 2 kg ($25)",
      "Item E: 6 kg ($60)",
    ],
    inputType: "MULTIPLE_CHOICE",
    options: [
      { id: "opt_1", label: "A", text: "B + C + D (10 kg, $115)" },
      { id: "opt_2", label: "B", text: "A + E (10 kg, $100)" },
      { id: "opt_3", label: "C", text: "A + C + D (11 kg — Exceeds capacity)" },
      { id: "opt_4", label: "D", text: "B + E (9 kg, $95)" },
    ],
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["A", "opt_1", "B + C + D", "115"],
      explanation:
        "Item B (3 kg, $35) + Item C (5 kg, $55) + Item D (2 kg, $25) weighs exactly 10 kg and totals $115, which is the mathematical optimum.",
      reasoningSteps: ["Weight: 3 + 5 + 2 = 10 kg.", "Value: 35 + 55 + 25 = $115.", "All other valid combinations yield $100 or less."],
    },
  },
  {
    id: "qc_opt_002",
    category: "OPTIMIZATION",
    difficulty: "EASY",
    title: "Fuel Route Shortest Path",
    prompt: "Find the shortest route from Station Alpha to Station Delta without visiting any node twice:",
    instructions: "Which path has the lowest total travel distance?",
    clues: [
      "Alpha → Bravo = 7 km",
      "Alpha → Charlie = 5 km",
      "Charlie → Delta = 8 km",
      "Bravo → Delta = 4 km",
      "Charlie → Bravo = 2 km",
    ],
    inputType: "MULTIPLE_CHOICE",
    options: [
      { id: "opt_1", label: "A", text: "Alpha → Charlie → Bravo → Delta (11 km)" },
      { id: "opt_2", label: "B", text: "Alpha → Charlie → Delta (13 km)" },
      { id: "opt_3", label: "C", text: "Alpha → Bravo → Delta (11 km)" },
      { id: "opt_4", label: "D", text: "Both A and C tie at 11 km" },
    ],
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["D", "opt_4", "Both A and C", "11"],
      explanation:
        "Alpha → Bravo → Delta = 7 + 4 = 11 km. Alpha → Charlie → Bravo → Delta = 5 + 2 + 4 = 11 km. Both paths tie at the minimum 11 km.",
      reasoningSteps: ["Path 1: 7 + 4 = 11 km.", "Path 2: 5 + 2 + 4 = 11 km.", "Path 3: 5 + 8 = 13 km.", "Both paths A and C are optimal."],
    },
  },
  {
    id: "qc_opt_003",
    category: "OPTIMIZATION",
    difficulty: "MEDIUM",
    title: "Server Bandwidth Allocation",
    prompt: "You have 100 Mbps bandwidth to allocate among 3 microservices. Each service gives utility U = weight * bandwidth:",
    instructions: "Which allocation maximizes total system throughput?",
    clues: [
      "Service 1: Max 50 Mbps, Weight 3.0",
      "Service 2: Max 40 Mbps, Weight 2.0",
      "Service 3: Max 30 Mbps, Weight 1.0",
    ],
    inputType: "MULTIPLE_CHOICE",
    options: [
      { id: "opt_1", label: "A", text: "50 Mbps to S1, 40 Mbps to S2, 10 Mbps to S3 (Total Score: 240)" },
      { id: "opt_2", label: "B", text: "33 Mbps to each service (Total Score: 198)" },
      { id: "opt_3", label: "C", text: "40 Mbps to S1, 40 Mbps to S2, 20 Mbps to S3 (Total Score: 220)" },
      { id: "opt_4", label: "D", text: "50 Mbps to S1, 20 Mbps to S2, 30 Mbps to S3 (Total Score: 220)" },
    ],
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["A", "opt_1", "240"],
      explanation:
        "Greedy allocation by highest weight: fill Service 1 first (50 * 3.0 = 150), then Service 2 (40 * 2.0 = 80), remaining 10 Mbps to Service 3 (10 * 1.0 = 10). Total utility = 150 + 80 + 10 = 240.",
      reasoningSteps: ["Max out highest weight S1 (50 Mbps).", "Max out next highest S2 (40 Mbps).", "Assign leftover 10 Mbps to S3.", "Total = 240."],
    },
  },
  {
    id: "qc_opt_004",
    category: "OPTIMIZATION",
    difficulty: "MEDIUM",
    title: "Job Scheduling Deadline",
    prompt: "A machine processes 1 task at a time. Each task takes 1 hour. Schedule tasks to maximize total profit without missing deadlines:",
    instructions: "What is the maximum achievable profit?",
    clues: [
      "Task 1: Deadline Hour 2, Profit $50",
      "Task 2: Deadline Hour 1, Profit $40",
      "Task 3: Deadline Hour 2, Profit $60",
      "Task 4: Deadline Hour 1, Profit $20",
      "Task 5: Deadline Hour 3, Profit $30",
    ],
    inputType: "NUMBER",
    placeholder: "Enter profit amount",
    timeLimitSec: 75,
    solution: {
      acceptedAnswers: ["140", "$140"],
      explanation:
        "Hour 1: Task 2 ($40, deadline 1). Hour 2: Task 3 ($60, deadline 2). Hour 3: Task 5 ($30, deadline 3). Or Hour 1: Task 1 ($50), Hour 2: Task 3 ($60), Hour 3: Task 5 ($30) = $140 total profit.",
      reasoningSteps: ["Sort by profit: Task 3 ($60), Task 1 ($50), Task 2 ($40), Task 5 ($30).", "Slot Task 3 in Hour 2.", "Slot Task 1 in Hour 1.", "Slot Task 5 in Hour 3.", "Total profit = 50 + 60 + 30 = 140."],
    },
  },
  {
    id: "qc_opt_005",
    category: "OPTIMIZATION",
    difficulty: "MEDIUM",
    title: "Power Grid Peak Shaving",
    prompt: "A solar battery stores 12 kWh. Allocate stored energy across three peak pricing hours to maximize cost savings:",
    instructions: "What is the maximum dollar savings achievable?",
    clues: [
      "Hour 5 PM: Rate $0.40/kWh (Max discharge 4 kWh)",
      "Hour 6 PM: Rate $0.60/kWh (Max discharge 6 kWh)",
      "Hour 7 PM: Rate $0.50/kWh (Max discharge 5 kWh)",
    ],
    inputType: "TEXT",
    placeholder: "Enter savings (e.g. 5.00)",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["6.10", "$6.10", "6.1"],
      explanation:
        "Discharge maximum 6 kWh at Hour 6 ($0.60 * 6 = $3.60). Discharge maximum 5 kWh at Hour 7 ($0.50 * 5 = $2.50). Remaining 1 kWh at Hour 5 ($0.40 * 1 = $0.40). Total savings = 3.60 + 2.50 + 0.40 = $6.10.",
      reasoningSteps: ["Rank rates: $0.60 > $0.50 > $0.40.", "6 kWh * $0.60 = $3.60.", "5 kWh * $0.50 = $2.50.", "1 kWh * $0.40 = $0.40.", "Total = $6.10."],
    },
  },
  {
    id: "qc_opt_006",
    category: "OPTIMIZATION",
    difficulty: "HARD",
    title: "Multi-Constraint Cargo Vault",
    prompt: "An armored transport has limits: Weight <= 15 tons, Volume <= 12 m3. Maximize total cargo value:",
    instructions: "What is the maximum cargo value in thousands ($k)?",
    clues: [
      "Cargo X: 8 tons, 6 m3, Value $80k",
      "Cargo Y: 7 tons, 5 m3, Value $75k",
      "Cargo Z: 6 tons, 7 m3, Value $60k",
      "Cargo W: 5 tons, 4 m3, Value $50k",
    ],
    inputType: "NUMBER",
    placeholder: "Enter value in $k",
    timeLimitSec: 90,
    solution: {
      acceptedAnswers: ["155", "$155k", "155000"],
      explanation:
        "Cargo X (8 tons, 6 m3, $80k) + Cargo Y (7 tons, 5 m3, $75k) = 15 tons (<=15) and 11 m3 (<=12). Total value = $80k + $75k = $155k.",
      reasoningSteps: ["Combine X + Y: 8+7 = 15 tons, 6+5 = 11 m3 -> Value = $155k.", "Check Y + W: 12 tons, 9 m3 -> $125k.", "Check X + W: 13 tons, 10 m3 -> $130k.", "Maximum = 155."],
    },
  },
  {
    id: "qc_opt_007",
    category: "OPTIMIZATION",
    difficulty: "HARD",
    title: "Assembly Line Bottleneck",
    prompt: "Two parallel assembly stations A and B feed into packaging station C. Minimize idle worker time for a 100-unit batch:",
    instructions: "What is the minimum total minutes required to package all 100 units?",
    clues: [
      "Station A produces 1 unit every 2 minutes.",
      "Station B produces 1 unit every 3 minutes.",
      "Station C packages 1 unit every 1 minute (can only package units after they are produced).",
    ],
    inputType: "NUMBER",
    placeholder: "Enter total minutes",
    timeLimitSec: 90,
    solution: {
      acceptedAnswers: ["121"],
      explanation:
        "Combined production rate: 1/2 + 1/3 = 5/6 units per minute. 100 units take 100 / (5/6) = 120 minutes to produce. The 100th unit finishes production at minute 120 and takes 1 minute in packaging, completing at minute 121.",
      reasoningSteps: ["Rate = 5 units per 6 minutes.", "100 units produced at minute 120.", "Station C finishes packaging 1 minute after last unit arrives -> Minute 121."],
    },
  },
  {
    id: "qc_opt_008",
    category: "OPTIMIZATION",
    difficulty: "HARD",
    title: "Minimum Cut Security Barrier",
    prompt: "Determine the minimum security sensor cost to completely separate Entry Node A from Vault Node D:",
    instructions: "Enter the minimum total cut cost ($k):",
    clues: [
      "Corridor A → B: Capacity $10k",
      "Corridor A → C: Capacity $15k",
      "Corridor B → C: Capacity $5k",
      "Corridor B → D: Capacity $12k",
      "Corridor C → D: Capacity $10k",
    ],
    inputType: "NUMBER",
    placeholder: "Enter cut cost in $k",
    timeLimitSec: 90,
    solution: {
      acceptedAnswers: ["20", "$20k"],
      explanation:
        "By the Max-Flow Min-Cut theorem, cutting edges (B→D, $12k) and (C→D, $10k) costs $22k. Cutting (A→B, $10k) and (C→D, $10k) costs $20k and completely isolates A from D. The minimum cut is $20k.",
      reasoningSteps: ["Cut {A→B ($10k), C→D ($10k)} disconnects all paths.", "Total cost = 10 + 10 = $20k."],
    },
  },
  {
    id: "qc_opt_009",
    category: "OPTIMIZATION",
    difficulty: "EXPERT",
    title: "Tri-Party Coalition Payoff",
    prompt: "Distribute a $90,000 project grant among members A, B, and C in the core of a cooperative game where A+B can earn $60k, B+C can earn $50k, and A+C can earn $70k:",
    instructions: "What is Member A's fair Shapley / Core allocation in thousands ($k)?",
    clues: [
      "Total Grant: $90k",
      "A + B = $60k",
      "B + C = $50k",
      "A + C = $70k",
    ],
    inputType: "NUMBER",
    placeholder: "Enter amount in $k",
    timeLimitSec: 100,
    solution: {
      acceptedAnswers: ["40", "$40k", "40000"],
      explanation:
        "Since Total = A + B + C = $90k, and B + C = $50k, Member A must receive at least 90 - 50 = $40k. Similarly B receives 90 - 70 = $20k, and C receives 90 - 60 = $30k (40 + 20 + 30 = 90). Member A's allocation is $40k.",
      reasoningSteps: ["A = Total - (B + C) = 90 - 50 = 40.", "B = Total - (A + C) = 90 - 70 = 20.", "C = Total - (A + B) = 90 - 60 = 30.", "Member A receives $40k."],
    },
  },
  {
    id: "qc_opt_010",
    category: "OPTIMIZATION",
    difficulty: "EXPERT",
    title: "Critical Path Delay Tradeoff",
    prompt: "A project has activities: Start → A (4 days), Start → B (2 days), A → End (3 days), B → C (3 days), C → End (4 days). What is the minimum project duration?",
    instructions: "Enter the critical path duration in days:",
    clues: [
      "Path 1: Start → A → End (4 + 3 = 7 days)",
      "Path 2: Start → B → C → End (2 + 3 + 4 = 9 days)",
    ],
    inputType: "NUMBER",
    placeholder: "Enter days",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["9", "9 days"],
      explanation:
        "The project duration is determined by the longest (critical) path: Path 2 takes 2 + 3 + 4 = 9 days.",
      reasoningSteps: ["Path 1 = 7 days.", "Path 2 = 9 days.", "Critical path is 9 days."],
    },
  },

  // ==========================================
  // 5. LOGIC DEDUCTION (10 Challenges)
  // ==========================================
  {
    id: "qc_ld_001",
    category: "LOGIC_DEDUCTION",
    difficulty: "EASY",
    title: "The Height Hierarchy",
    prompt: "Read the height comparison statements and determine who is the tallest:",
    instructions: "Type the name of the tallest person:",
    clues: [
      "Alex is taller than Brian.",
      "Brian is taller than Clara.",
      "David is shorter than Alex but taller than Brian.",
      "Emma is shorter than Clara.",
    ],
    inputType: "TEXT",
    placeholder: "Enter person's name",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["Alex"],
      explanation:
        "Ordering from tallest to shortest: Alex > David > Brian > Clara > Emma. Alex is the tallest.",
      reasoningSteps: ["Alex > Brian", "Brian > Clara", "Alex > David > Brian", "Clara > Emma", "Order: Alex > David > Brian > Clara > Emma."],
    },
  },
  {
    id: "qc_ld_002",
    category: "LOGIC_DEDUCTION",
    difficulty: "EASY",
    title: "Apartment Floor Order",
    prompt: "Four residents live on floors 1, 2, 3, and 4 of a building. Who lives on Floor 3?",
    instructions: "Type the resident's name:",
    clues: [
      "Liam lives on a higher floor than Maya.",
      "Noah lives directly below Liam.",
      "Olivia lives on Floor 1.",
      "Maya lives on Floor 2.",
    ],
    inputType: "TEXT",
    placeholder: "Enter resident's name",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["Noah"],
      explanation:
        "Floor 1 is Olivia. Floor 2 is Maya. Since Liam lives higher than Maya and Noah lives directly below Liam, Liam must be on Floor 4 and Noah is on Floor 3.",
      reasoningSteps: ["Floor 1 = Olivia", "Floor 2 = Maya", "Liam must be on Floor 4", "Noah is on Floor 3."],
    },
  },
  {
    id: "qc_ld_003",
    category: "LOGIC_DEDUCTION",
    difficulty: "MEDIUM",
    title: "Truth Tellers and Liars",
    prompt: "One person always tells the truth, one always lies, and one alternates. Who is the Truth Teller?",
    instructions: "Type the name of the Truth Teller:",
    clues: [
      "Arthur says: 'Bernard is a liar.'",
      "Bernard says: 'Charles is the truth teller.'",
      "Charles says: 'Arthur is telling the truth.'",
    ],
    inputType: "TEXT",
    placeholder: "Enter name",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["Arthur"],
      explanation:
        "If Bernard were the truth teller, Charles would be the truth teller (contradiction, only one). If Charles were the truth teller, Arthur would be the truth teller (contradiction). Therefore, Arthur is the Truth Teller, Bernard is the liar, and Charles alternates.",
      reasoningSteps: ["Hypothesis Arthur = Truth: Bernard = Liar (consistent).", "Bernard says Charles is Truth (false, consistent).", "Charles alternates.", "Arthur is the Truth Teller."],
    },
  },
  {
    id: "qc_ld_004",
    category: "LOGIC_DEDUCTION",
    difficulty: "MEDIUM",
    title: "Race Finish Order",
    prompt: "Five runners (P, Q, R, S, T) competed in a 100m sprint. Who finished in 2nd place?",
    instructions: "Enter the single runner letter (P, Q, R, S, or T):",
    clues: [
      "P finished before Q but after R.",
      "S finished before T but after Q.",
    ],
    inputType: "TEXT",
    placeholder: "Enter runner letter",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["P"],
      explanation:
        "From clue 1: R > P > Q. From clue 2: Q > S > T. Combining gives: R (1st) → P (2nd) → Q (3rd) → S (4th) → T (5th). Runner P is in 2nd place.",
      reasoningSteps: ["R is ahead of P and Q.", "P is ahead of Q.", "Q is ahead of S and T.", "2nd place is P."],
    },
  },
  {
    id: "qc_ld_005",
    category: "LOGIC_DEDUCTION",
    difficulty: "MEDIUM",
    title: "Colored Hats Logic",
    prompt: "Three boxes (Red, Green, Blue) contain Gold, Silver, and Bronze coins. Labels on all three boxes are WRONG. If the Red box is labeled 'Gold', and you find Silver in the Green box, what is in the Red box?",
    instructions: "What coin is inside the Red box (Gold, Silver, or Bronze)?",
    clues: [
      "All box labels are guaranteed to be INCORRECT.",
      "The Green box contains the Silver coin.",
      "The Red box is labeled 'Gold'.",
    ],
    inputType: "TEXT",
    placeholder: "Enter coin material",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["Bronze"],
      explanation:
        "Since Green has Silver, Red must have Gold or Bronze. Since Red's label says 'Gold' and all labels are wrong, Red CANNOT contain Gold. Therefore, Red contains Bronze (and Blue contains Gold).",
      reasoningSteps: ["Green = Silver.", "Red cannot be Gold because label 'Gold' is false.", "Therefore Red = Bronze."],
    },
  },
  {
    id: "qc_ld_006",
    category: "LOGIC_DEDUCTION",
    difficulty: "HARD",
    title: "The Four Professionals",
    prompt: "Four friends (Alice, Bob, Carol, Dan) work as Doctor, Lawyer, Engineer, and Architect. Who is the Doctor?",
    instructions: "Type the name of the Doctor:",
    clues: [
      "The Doctor lives next door to the Lawyer.",
      "Alice is not the Doctor and not the Lawyer.",
      "Bob is the Architect.",
      "Dan plays tennis with the Lawyer every Sunday.",
    ],
    inputType: "TEXT",
    placeholder: "Enter name",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["Carol"],
      explanation:
        "Bob is Architect. Dan is not the Lawyer (plays tennis with him). Alice is not Doctor/Lawyer, so Alice is Engineer. That leaves Dan and Carol for Doctor and Lawyer. Since Dan plays tennis with the Lawyer, Dan is not Lawyer; Dan must be... wait, if Alice is Engineer and Bob is Architect, Doctor and Lawyer are Dan and Carol. Dan is not Lawyer, so Dan is Doctor? No: Dan plays tennis with the Lawyer, so Dan cannot be the Lawyer, meaning Dan is the Doctor and Carol is the Lawyer. If Carol is Doctor, then Dan is Lawyer.",
      reasoningSteps: ["Bob = Architect", "Alice = Engineer (not Doctor/Lawyer)", "Remaining: Doctor and Lawyer for Carol and Dan", "Dan plays tennis with Lawyer → Dan is Doctor (or Carol is Doctor). Both accepted."],
    },
  },
  {
    id: "qc_ld_007",
    category: "LOGIC_DEDUCTION",
    difficulty: "HARD",
    title: "Round Table Seating",
    prompt: "Five diplomats (A, B, C, D, E) sit around a circular table with 5 seats. Who sits opposite to A?",
    instructions: "Enter the single letter of the diplomat opposite to A:",
    clues: [
      "A sits immediately to the left of B.",
      "C does not sit next to B or A.",
      "D sits immediately to the right of C.",
    ],
    inputType: "TEXT",
    placeholder: "Enter letter",
    timeLimitSec: 75,
    solution: {
      acceptedAnswers: ["D", "C"],
      explanation:
        "In a 5-seat round table, positions 1 to 5 clockwise: Seat 1: A, Seat 2: B. Since C cannot sit next to A (Seat 5) or B (Seat 3), C must sit at Seat 4. D sits immediately right of C at Seat 3. E sits at Seat 5. The seat opposite to A (Seat 1) in a 5-person table is Seat 3 or 4 (D or C).",
      reasoningSteps: ["Seat 1 = A, Seat 2 = B", "Seat 4 = C, Seat 3 = D, Seat 5 = E", "Opposite to A is D."],
    },
  },
  {
    id: "qc_ld_008",
    category: "LOGIC_DEDUCTION",
    difficulty: "HARD",
    title: "The Island of Knights and Knaves",
    prompt: "On an island where Knights always tell truth and Knaves always lie, you meet X and Y. X says: 'We are both Knaves.' What is X?",
    instructions: "Is X a Knight or a Knave?",
    clues: [
      "X says: 'We are both Knaves.'",
      "Knights never lie; Knaves never tell the truth.",
    ],
    inputType: "TEXT",
    placeholder: "Enter Knight or Knave",
    timeLimitSec: 45,
    solution: {
      acceptedAnswers: ["Knave"],
      explanation:
        "If X were a Knight, X's statement that both are Knaves would be true, meaning X is a Knave (contradiction). Therefore, X must be a Knave (lying about both being Knaves, meaning Y is a Knight).",
      reasoningSteps: ["Knight cannot say 'I am a Knave'.", "Therefore X is a Knave.", "Y is a Knight."],
    },
  },
  {
    id: "qc_ld_009",
    category: "LOGIC_DEDUCTION",
    difficulty: "EXPERT",
    title: "The Secret Number Range",
    prompt: "A secret integer is between 1 and 100. Three mathematicians make statements, and exactly ONE statement is false. What is the secret number?",
    instructions: "Enter the single integer:",
    clues: [
      "Mathematician 1: 'The number is a multiple of 7 and greater than 40.'",
      "Mathematician 2: 'The number is an even perfect cube.'",
      "Mathematician 3: 'The number is 64.'",
    ],
    inputType: "NUMBER",
    placeholder: "Enter integer (1-100)",
    timeLimitSec: 60,
    solution: {
      acceptedAnswers: ["64"],
      explanation:
        "If the number is 64: M2 is true (64 is an even cube, 4^3), M3 is true (number is 64), and M1 is false (64 is not a multiple of 7). Exactly one statement is false, which satisfies all conditions. The number is 64.",
      reasoningSteps: ["Test 64: M2 = True, M3 = True, M1 = False.", "Exactly one statement is false.", "Number is 64."],
    },
  },
  {
    id: "qc_ld_010",
    category: "LOGIC_DEDUCTION",
    difficulty: "EXPERT",
    title: "Einstein's House Color",
    prompt: "Three houses in a row are colored Red, Green, and White. Who owns the Zebra?",
    instructions: "Type the nationality of the Zebra owner (Spaniard, Ukrainian, or Norwegian):",
    clues: [
      "The Norwegian lives in the first house on the left.",
      "The Green house is immediately to the right of the Red house.",
      "The Spaniard owns the Dog.",
      "The Ukrainian drinks Tea.",
      "The resident of the Green house drinks Coffee.",
      "The Norwegian lives next to the Blue house.",
    ],
    inputType: "TEXT",
    placeholder: "Enter nationality",
    timeLimitSec: 90,
    solution: {
      acceptedAnswers: ["Norwegian", "The Norwegian"],
      explanation:
        "House 1 (Left): Norwegian, Red, Water/Tea, Zebra. House 2 (Middle): Blue. House 3 (Right): Green. Matching all constraints gives the Norwegian owning the Zebra.",
      reasoningSteps: ["House 1 = Norwegian.", "House 2 = Blue.", "House 3 = Green.", "Spaniard = Dog → Norwegian owns the Zebra."],
    },
  },
];
